### ISSUE TITLE
config.json and status_check.sh not in directory?

### ISSUE THREAD

**Issue by careyjames** [its-a-feature/Mythic#108]
I am logged in and its running in my web browser but i could not find:
config.json and status_check.sh not in the directory?
~/Mythic

**Comment by its-a-feature** [comment]
In Mythic 2.2.* those files are no longer there. 
All configuration is moved to `Mythic/.env` and the `status_check.sh` functionality is now part of the `mythic-cli` binary: `sudo ./mythic-cli status`
