### ISSUE TITLE
Payload build failed

### ISSUE THREAD

**Issue by P-T001** [its-a-feature/Mythic#111]
hi，
When I build the payload, the following error occurs. I need to run: "go env - w goproxy= https://goproxy.cn ”, I want to ask where the go environment for building payload is

error message:
[STDERR]
go: github.com/djherbis/atime@v1.0.0: Get https://proxy.golang.org/github.com/djherbis/atime/@v/v1.0.0.mod: dial tcp 172.217.160.81:443: connect: connection refused
/build/poseidon-linux-amd64 does not exist

**Comment by P-T001** [comment]
I have solved this problem, enter the docker of the relevant payload, and run the following command
go env - w goproxy"= https://goproxy.cn
go env -w GO111MODULE=on

**Comment by its-a-feature** [comment]
Can you provide more information about this? Which payload are you referring to?

**Comment by its-a-feature** [comment]
I just pulled down the poseidon repo via `sudo ./mythic-cli install github https://github.com/MythicAgents/poseidon` and was able to generate the payload. Are you able to provide more information about your setup/configuration?

**Comment by P-T001** [comment]
According to this error message, I found that other people also have this problem on the Internet, and then I need to add this variable to the go environment for building the file. The reason may be that the original goproxy is blocked by firewalls in countries and regions.

The test environment system I use is kali-linux-2020.2-amd64
Go version go1.13.4 Linux / AMD64 is used in the docker of payload

Payload uses Poseidon, c2profiles uses HTTP, and then sets http://IP , others are the default settings

**Comment by its-a-feature** [comment]
Ah yeah, it appears to be an issue based on the area. It's probably an easier fix for you to modify the Dockerfile rather than having to `docker exec` into the container yeah?

**Comment by P-T001** [comment]
I don't know where the dockerfile of Poseidon container is. Docker exec will be more convenient for me

**Comment by its-a-feature** [comment]
Ah, every Payload Type has their Dockerfile in the same location:
```
Mythic/Payload_Types/[payload name]/Dockerfile
```
the advantage to making the change there is that if you need to restart Mythic for some reason, then your change will be automatically re-applied when the container comes back up again.

**Comment by P-T001** [comment]
he effect of modifying dockerfile will be better. Thank you very much for your help
