### ISSUE TITLE
Provide advice

### ISSUE THREAD

**Issue by P-T001** [its-a-feature/Mythic#112]
hi,
I think mythic has complete functions and strong compatibility, but I still have some small problems after passing the test。
This test uses  payload：poseidon/  c2profiles：http
Put forward some suggestions according to the use experience:
1.“Browser Scripts”:The command document of "browser scripts" does not provide detailed usage examples, but only describes the parameters. For example, "usage" in Poseidon's portscan only gives the command itself,
    It is recommended that the browser scripts command usage be displayed on the command line or that a tab be added in the actions of each script in browser scripts to display its usage.

2.“Command line callback”：Whether the record of the input command can filter the execution of the wrong command or delete the wrong command.

3.“File browser”： When you left click the unopened file directory, it does not refresh. You need to click list to view the files under the file directory.

**Comment by its-a-feature** [comment]
Hi! Thank you for providing feedback about the user experience. I have some clarifying questions:

1.  Are you referring to "browser scripts" which are the scripts that allow you to turn structured output into HTML components (like tables), the help dialog when you type "help portscan", or are you referring to the modal popup after you just type `portscan` and hit enter? 
2. Are you talking about when you hit the up and down arrow on the command line and it cycles through the commands you've already entered on that callback? you're wanting that filtered somehow?
3. When you click the "folder" icon for the file browser - if it's open, the folder is just collapsed. If it's closed, Mythic fetches the data that's stored in Mythic's database and displays it on the side. If you click "list" then that signifies to Mythic to issue a new task to the agent to list files. Is this not the behavior you're seeing?

**Comment by P-T001** [comment]
1.I didn't expect that after directly entering portscan, a window that can input host and port will pop up. I thought it was to enter parameters like entering a command

2.You can set the command not to display errors in "filter viewable tasks"

3.I mean, if the file directory of “ls” is not used, clicking the file directory with the mouse will automatically launch ls. There is no need to manually click “list” or enter “ls”

4.I use ". / mythic cli install GitHub https://github.com/MythicAgents/apollo ”When installing the payload, the live event feed on the web interface displays the following marked red  ，but it does not affect the construction of payload and callback
When I install Poseidon, it will also be displayed in subscript red：
 
apollo supports the wrapper, service_wrapper, but it doesn't currently exist within Mythic

apollo's sync with Mythic failed:
duplicate key value violates unique constraint "payloadtype_ptype"
DETAIL:  Key (ptype)=(apollo) already exists.

Failed Sync-ed database import with apollo payload files: duplicate key value violates unique constraint "payloadtype_ptype"
DETAIL:  Key (ptype)=(apollo) already exists.

**Comment by its-a-feature** [comment]
These should be addressed in the new UI
