### ISSUE TITLE
Unable to add operators to operation by name

### ISSUE THREAD

**Issue by hyphus** [its-a-feature/Mythic#114]
I was updating some automation used to create operators to work with the newest version and ran into an issue.

Using the sample code with minor modifications (more on that below) it appears specifying an operation by name no longer works as expected.

```root@mythic:/opt/Mythic# python3 repro.py
[+] Logging into Mythic
[*] Connecting to Mythic as scripting_version 3
Traceback (most recent call last):
  File "repro.py", line 28, in <module>
    asyncio.run(scripting())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "repro.py", line 24, in scripting
    await mythic.add_or_update_operator_for_operation(operation=operation, operator=new_operator_resp.response)
  File "/usr/local/lib/python3.8/dist-packages/mythic/mythic_rest.py", line 1809, in add_or_update_operator_for_operation
    resp = await self.get_operation(operation)
  File "/usr/local/lib/python3.8/dist-packages/mythic/mythic_rest.py", line 1786, in get_operation
    if o.name == operation.name:
AttributeError: 'Operation' object has no attribute 'name'
```

Referencing the Operation by id does work as expected.
`operation = mythic_rest.Operation(id=1)`

I've tried this with two different Mythic instances, one built with automation and one built fresh manually today.

Mythic server version: v2.2.13
Mythic pip version: 0.0.23
Python 3.8.10
Ubuntu 20.04

Stepping through the code the [response returned](https://github.com/MythicMeta/Mythic_Scripting/blob/master/mythic/mythic_rest.py#L1783) from `get_all_operations()` contains the name property in the raw response.

![image](https://user-images.githubusercontent.com/26208889/129666961-9a4b0913-353d-407d-82ac-7ceba71ce763.png)

However, the returned Operation object does not have the name property.

![image](https://user-images.githubusercontent.com/26208889/129667665-ccddfdce-c6c8-4e24-b3ac-e0ef3864797c.png)

I _think_ the issue is that in [the Operation class definition](https://github.com/MythicMeta/Mythic_Scripting/blob/master/mythic/mythic_rest.py#L67) the init function takes name as a parameter but is missing the assignment (`self.name = name`) like the other properties.

I added that assignment to my installed version and it worked as expected. However, I'm not sure if that's the correct fix or not.

Additionally, when looking at the documentation and scripting examples I noticed that the example for adding operators has a couple minor bugs.
https://docs.mythic-c2.net/scripting/scripting-examples#creating-users-and-adding-them-to-an-operation

Line 18 should be `new_operator` instead of `honeycrisp` for the Operator object.

The dummy password on line 16 doesn't meet the default password complexity requirements which throws an exception.

```
Traceback (most recent call last):
  File "repro.py", line 28, in <module>
    asyncio.run(scripting())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "repro.py", line 20, in scripting
    new_operator_resp = await mythic.create_operator(new_operator)
  File "/usr/local/lib/python3.8/dist-packages/mythic/mythic_rest.py", line 1963, in create_operator
    raise Exception("Unable to create operator and no active operator found: " + json.dumps(resp, indent=2, default=lambda o: o.to_json()))
Exception: Unable to create operator and no active operator found: {
  "response_code": 200,
  "raw_response": {
    "error": "password must be at least 12 characters long"
  },
  "status": "error",
  "response": {
    "error": "password must be at least 12 characters long"
  }
}
```

**Comment by its-a-feature** [comment]
You're absolutely right! I really appreciate the amount of information you provided with this issue. I updated the Mythic PyPi Package (0.0.24) with the fix (just like you mentioned), and I updated the corresponding documentation for those two lines.

**Comment by hyphus** [comment]
Awesome, thank you for the quick response!
Just pulled the new version and it works great.
