### ISSUE TITLE
Websocket behind Apache2 Reverse Proxy

### ISSUE THREAD

**Issue by russokiwi** [its-a-feature/Mythic#115]
Hi, I need to have the UI accessible via a reverse proxy.  Apache in this instance is implemented. Mythic UI is complaining loud and clear there's no websockets connectivity - although the interface is drawn fine.  Would you have any suggestions for apache rewrite / proxy rules ? I understand 7443 should be the only exposed port, though I'm not entirely sure on websocket fits.  Thanks very much.

**Comment by benichmt1** [comment]
@russokiwi is this what you're experiencing? I ran into this when not accessing mythic through a normal tunnel (127.0.0.1:7443 in the browser)

![image](https://user-images.githubusercontent.com/1136610/131556430-1bd2344b-c0d9-4c18-ae2f-04c7c7d6b5f0.png)

**Comment by russokiwi** [comment]
> @russokiwi is this what you're experiencing? I ran into this when not accessing mythic through a normal tunnel (127.0.0.1:7443 in the browser)
> 
> ![image](https://user-images.githubusercontent.com/1136610/131556430-1bd2344b-c0d9-4c18-ae2f-04c7c7d6b5f0.png)

yes.  I ended up using NGINX to solve the issue.

**Comment by russokiwi** [comment]
awesome, thanks!  I rewrote config in NGINX, - workaround but a solution - all's working now.
