### ISSUE TITLE
How do we use piped shell commands?

### ISSUE THREAD

**Issue by Viss** [its-a-feature/Mythic#119]
I have shells using medusa, and I'm trying to bump my way up to poseidon shells, but troublehsooting getting that second implant to fire it seems I can't to this:

```ps auxwww | grep payload```

What's the proper way to use pipes in shell commands via mythic?

**Comment by its-a-feature** [comment]
Are you doing this within the `medusa` agent? Mythic is just the controller and leaves that sort of implementation details up to the agent authors.

**Comment by Viss** [comment]
yeah, im trying to do a "shell" command from the mythic ui, where the payload is medusa and it looks like there might be some escaping issues with certain chars - the pipe is the first one i found
