### ISSUE TITLE
I cant find Mythic/.env but mythic service is started successfully after exceuting:: sudo ./mythic-cli mythic start

### ISSUE THREAD

**Issue by IAMinZoho** [its-a-feature/Mythic#130]
Please check this and let me know what am i doing wrong:

──(root💀C2)-[/opt/Mythic]
└─# sudo ./mythic-cli config get MYTHIC_ADMIN_PASSWORD
MYTHIC_ADMIN_PASSWORD = HcY5EJObFHFdFeZuLqXgmW9XXXXX
                                                                             
┌──(root💀C2)-[/opt/Mythic]
└─# Mythic/.env
zsh: no such file or directory: Mythic/.env
                                                                             
┌──(root💀C2)-[/opt/Mythic]
└─#

**Comment by its-a-feature** [comment]
what is it you're trying to do with the .env file? what if you do `ls -al` for the current folder (`/opt/Mythic` in your case)

**Comment by IAMinZoho** [comment]
> what is it you're trying to do with the .env file? what if you do `ls -al` for the current folder (`/opt/Mythic` in your case)

Thanks for the quick response. I want to see the configurations.  The `/opt/Mythic` shows me a `.env`. How can i open it ? Please suggest me a command.

**Comment by IAMinZoho** [comment]
> > what is it you're trying to do with the .env file? what if you do `ls -al` for the current folder (`/opt/Mythic` in your case)
> 
> Thanks for the quick response. I want to see the configurations. The `/opt/Mythic` shows me a `.env`. How can i open it ? Please suggest me a command.

I got it ` mousepad .env`

Thank you for your help!
