### ISSUE TITLE
Agents on arch linux

### ISSUE THREAD

**Issue by sly9it** [its-a-feature/Mythic#134]
Please i tried to setting up on arch linux with quite a success on mythic setup but came to a stand still when a number of agents didn't start up so i went on installing files needed in the Agent installation scripts but still some agents did not come up 

Even tried installing apt too 

Atlas 
Apollo
Poseidon 
Medusa

Thanks

**Comment by its-a-feature** [comment]
I need more information from you to try to help. What errors are you getting? I haven't tested anything on arch linux

**Comment by sly9it** [comment]
Default apt package manager applications needed for arch linux 

Unable to install correctly due to this issues 

For the above agents

**Comment by its-a-feature** [comment]
Arch Linux (and other os/architecture platforms) are currently not supported because there are a lot of underlying Docker related components/containers that would need to be updated (as you're seeing). It's on the roadmap to support this sort of thing, but it's currently not supported
