### ISSUE TITLE
Change install_docker_ubuntu.sh script's curl command to install docker-compose 1.25 instead of 1.24

### ISSUE THREAD

**Issue by jsarkisian** [its-a-feature/Mythic#136]
Please

**Comment by jsarkisian** [comment]
There’s a tool I use that pulls from this repo. I’m not sure if others have issues, but when using this, 1.24 causes my `docker-compose build` command to hang. Using 1.25 in place of it fixes the issue.

**Comment by its-a-feature** [comment]
This is updated to 1.25
