### ISSUE TITLE
Error Callback Payload Appfell

### ISSUE THREAD

**Issue by slamet404** [its-a-feature/Mythic#137]
after connect callback , try command shell or more command not working 

Pop up Notification "shell isn't in the current callback"
![call back error](https://user-images.githubusercontent.com/5875641/149118828-71c9809b-e9f4-48c1-af85-af7580f54deb.png)

any solution for this ?

Thanks

**Comment by its-a-feature** [comment]
Can you click the dropdown next to the number 4 for your callback and then select "Metadata". You should then see a list of commands that are loaded into the agent. If `shell` isn't listed there, then that would be why you can't issue that task to the agent. If you have `load` in there, then you can do `load shell` and then after that completes successfully, you can run the shell command.

**Comment by slamet404** [comment]
i think when create payload notif no commands selected
but i click example shell and next click create same popup notif

![creat](https://user-images.githubusercontent.com/5875641/149177876-1030bb22-59ba-4e8c-a8f6-0b1064b360f4.png)

**Comment by slamet404** [comment]
https://user-images.githubusercontent.com/5875641/149178611-cb4c337f-76d6-4c11-b8ff-74238109211d.mov

**Comment by its-a-feature** [comment]
Yeah, those are two _different_ messages. The first one is saying that you didn't select _anything_ to be in the agent. So, you selected `shell`. The second one is telling you that you don't have any command that supports `exit` in the agent, so you won't be able to kill the agent from the Mythic UI. That's also an issue for normal operations, so Mythic is making you accept that risk too.

**Comment by slamet404** [comment]
oh yes sorry im mistake create payload and select command, im create again payload

**Comment by slamet404** [comment]
![solved](https://user-images.githubusercontent.com/5875641/149180620-5d605cf6-a5d9-4929-820e-d15141aa541a.png)

solved
Thanks for confirmation
