### ISSUE TITLE
Invalid Hostname

### ISSUE THREAD

**Issue by Pickfordmatt** [its-a-feature/Mythic#14]
Hi,

I'm having a slight issue with regards to the Mac Hostname running a JXA payload, I've attached an image for example. The hostname returned by the shell command is correct however the one on the implant table is incorrect. The name within the implant table is a valid hostname for a device unrelated to the implant.

**Comment by its-a-feature** [comment]
Did you attach an image?

**Comment by Pickfordmatt** [comment]
ta da, apologies. 
![Screenshot 2020-01-14 at 16 01 30](https://user-images.githubusercontent.com/3343862/72423232-d149c800-377b-11ea-920f-5f063379f2a3.png)

**Comment by its-a-feature** [comment]
Hm, ok so from your agent, run the following command:
`jscript $.NSProcessInfo.processInfo.hostName.js` 
that command gets the name of the host on which your current process is running. This is the API call that gets executed to pull out that hostname you see at the top (https://developer.apple.com/documentation/foundation/nsprocessinfo/1417236-hostname?language=objc).

Macs also have a few other hostnames they can go by depending on if they're AD joined and what task is being done. You can see a few of these other names by running:
`jscript ObjC.deepUnwrap($.NSHost.currentHost.names)` 
from your agent as well.

From those commands, do you see the two variations of hostnames?
