### ISSUE TITLE
All cookies should be scoped to ip and port

### ISSUE THREAD

**Issue by ineffectivecoder** [its-a-feature/Mythic#140]
We have a use case for running more than 1 instance of Mythic. Our configuration results in more than one instance appearing on one ip but available on different ports via ssh port forwarding. Due to the this, the cookies used for auth and refresh are only bound to the ip and not the port. The result is us getting logged out of the other interface every time we login to a new instance. Please investigate binding the cookies to the url and port. Thank you!

**Comment by its-a-feature** [comment]
The next major version of Mythic will have HttpOnly and Strict mode for same site origin. These together should achieve what you're requesting
