### ISSUE TITLE
HTTP Headers in C2-Profile Instance missing

### ISSUE THREAD

**Issue by HanseSecure** [its-a-feature/Mythic#143]
Used Version: 
2.3.7 

While saving a c2 instance i cant define http header

![grafik](https://user-images.githubusercontent.com/24669088/151925742-bbe10300-8402-478f-9035-a1371fde5a7a.png)

But while creating a payload and using a new instance i define these

![grafik](https://user-images.githubusercontent.com/24669088/151925814-d253381d-8dfe-4a64-a3f7-2c1b9b658321.png)

**Comment by its-a-feature** [comment]
oh interesting, it's just when you save a c2 instance that the headers get lost?

**Comment by HanseSecure** [comment]
while creating a new one through the c2-profile manager (not creating a payload)

**Comment by its-a-feature** [comment]
oh, yup, that's super weird that it's just gone in that view. I'll investigate tomorrow and get a fix pushed. You're still able to create a payload manually though right?

**Comment by HanseSecure** [comment]
yes its possible and the useragent is working through the payload generation

**Comment by its-a-feature** [comment]
Just made a push for this which should fix it in the UI for you. Let me know if you still have issues

**Comment by HanseSecure** [comment]
Fixed

![grafik](https://user-images.githubusercontent.com/24669088/152063241-982dd0f7-2729-41f1-b117-9b4b1e69290f.png)
