### ISSUE TITLE
UI crashes if file listing results include an invalid date

### ISSUE THREAD

**Issue by kylewillmon** [its-a-feature/Mythic#169]
After updating a custom agent to Mythic 2.3, I now have issues with the file browser crashing. The page goes blank and the console shows this error:

```
RangeError: invalid date
    _G CallbacksTabsFileBrowserTable.js:305
    Z CallbacksTabsFileBrowserTable.js:148
    Z CallbacksTabsFileBrowserTable.js:139
    Z CallbacksTabsFileBrowserTable.js:135
    React 2
    xG CallbacksTabsFileBrowserTable.js:133
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    D scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    36813 scheduler.production.min.js:12
    Webpack 10
react-dom.production.min.js:216:199
```

The dates returned by our custom agent are just Windows `FILETIME` values as a string. They are not currently human readable dates and this is something that we will need to change in our agent. But even so, this should not crash the UI.

This was tested in Firefox 97.0

**Comment by its-a-feature** [comment]
The file browser is expecting unix epoch timestamps

**Comment by kylewillmon** [comment]
My agent is using unmodified Windows epoch timestamps right now. The only change it does is converting them to strings. So they currently look like this:

```
"modify_time": "132399934738436133",
```

**Comment by its-a-feature** [comment]
just updated this in the latest merge
