### ISSUE TITLE
Update caused loss of users and operations

### ISSUE THREAD

**Issue by ZerkerEOD** [its-a-feature/Mythic#178]
How is it possible to update without losing user-profiles and operations?

I just came back to my instance because I was told that no Listener was working. I updated and now everything we had is not gone. I followed the information posted in the documentation on how to update.

**Comment by its-a-feature** [comment]
Hey! I'm sorry that happened to you. Let's see what we can do. Can you provide anymore information?

**Comment by ZerkerEOD** [comment]
I am not sure what broke originally. I had an employee message me saying all the listeners were down and he was unable to start any of them and the lights for all were red. I then did a `./mythic-cli stop` and `./mythic-cli start` Still unable to connect. Looked at the logs and was getting a lot of errors saying that the profile 12 was not compatible and it needed version 8 or 9. So I figured somehow the profiles were updated and not the mythic instance. I was on version 2.2.# (unsure exactly) but saw that 2.3.7 was the latest. So I decided to update mythic and all profiles and payloads. 

So I tried following the directions by resetting the database, deleting the .env file and doing a pull. I was having issues with the pull as it was mentioning something about an apfell logo being altered locally. I didn't care about that so I did a:

git fetch 
git add *
git stash
git merge

which allowed me to pull the new version. I also then reran all the ./mythic-cli install github to update everything. 

From there I ran the ./mythic-cli start and was having an error for Nimplant. Said nimplant was not found, so looked up in the system and saw that it was installed as Nimplant and not nimplant so I changed the files name to lowercase and the build was successful. Then went to log in and realized no users carried over, and all operation data was gone. I figure that happened from the database reset but the instructions clearly say you have to do that in order to upgrade.

**Comment by ZerkerEOD** [comment]
Is there a method to export what is needed and import it into the new? Otherwise, it makes it really hard to update. Since we are running it on digital ocean I think someone tried to update it without my knowledge as I am over the implementation of it for us.

**Comment by its-a-feature** [comment]
Right now there's not a method to do that. It's on my roadmap to add when I redo the entire back-end server for Mythic though
