### ISSUE TITLE
Wrapper payloads don't properly support BuildParameterTypes.Boolean

### ISSUE THREAD

**Issue by guac1** [its-a-feature/Mythic#179]
## Expected Behavior
Wrapper payloads with BuildParameterType.Boolean parameters should display properly in the frontend, just like normal payloads.

## Current Behavior
BuildParameterType ChooseMultiple and Boolean do not allow the user to select a value:

![bug](https://user-images.githubusercontent.com/63883096/156887734-bd607d3f-edf2-4b47-a17a-0174cc0b993b.png)

## Steps to Reproduce

Create an empty PayloadType (by copying the example payload type) and replace builder.py with this:

```python3
from mythic_payloadtype_container.PayloadBuilder import *
from mythic_payloadtype_container.MythicCommandBase import *

class Bugreport(PayloadType):
    name = "bugreport"
    file_extension = "exe"
    author = "abcdefg"
    supported_os = [SupportedOS.Windows]
    wrapper = True
    wrapped_payloads = []
    note = """Bug test"""
    supports_dynamic_loading = False 
    build_parameters = [
        BuildParameter(
            name="bool_param",
            parameter_type=BuildParameterType.Boolean,
            description="BuildParameterType.Boolean",
            default_value=True
        ),
        BuildParameter(
            name="str_param",
            parameter_type=BuildParameterType.String,
            description="BuildParameterType.String",
            default_value=""
        ),
        BuildParameter(
            name="choose_one_param",
            parameter_type=BuildParameterType.ChooseOne,
            description="BuildParameterType.ChooseOne",
            choices=["choice1", "choice2", "choice3"],
        ),
    ]
    c2_profiles = []

    async def build(self) -> BuildResponse:
        resp = BuildResponse(status=BuildStatus.Error)
        return resp
```

Then try to create a wrapper payload in the Web UI. 
When changing `wrapper = True` to `wrapper = False` and restarting the payload type, the option appears correctly.

**Comment by its-a-feature** [comment]
Just made a push to the master branch, PR#180, pull the update and let me know if it's fixed. I realized that I had the boolean logic for the payload creation page but somehow missed it for the payload wrapper page

**Comment by guac1** [comment]
Seems to be fixed, thanks!

**Comment by guac1** [comment]
Sorry, I spoke to soon. The toggle does display now, but it still ignores the `default_value` and instead always defaults to `True`. The default value works properly with normaly payloads.

**Comment by its-a-feature** [comment]
Ah, good catch! My test case had it as True so i didn't notice. The PR #181 should fix it

**Comment by guac1** [comment]
Fixed 👍 Thank you :)
