### ISSUE TITLE
Postgres container seems outdated

### ISSUE THREAD

**Issue by mike-t225** [its-a-feature/Mythic#186]
I am having issues which seems are due to outdated postgres docker container. (mythic_postgres:0.0.2) 
First of all, it seems it is missing pgcrypto extensions. I get errors about missing gen_random_uuid function.
I am also having issues with some queries that seem require postgres 9.5, but postgres 9.4 is installed. The query uses ON CONFLICT statements that were added in 9.5. Can you please verify?

**Comment by its-a-feature** [comment]
hm.. mythic_postgres:0.0.2 is the current version. Where are you seeing these errors? Also, what version of Mythic are you using?

**Comment by mike-t225** [comment]
I don't know, maybe I am doing something wrong, but this is what I get:

1. Issue with "gen_random_uuid"
I have downloaded master, but, from what I see, the 2.3.7 tag will have the same as the use of gen_random_uuid function is already there. The error I am seeing is right after running ./mythic-cli start.
It is trying to create a fresh database and the error is:
```
Traceback (most recent call last):
  File "/usr/local/bin/python3.8/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.UndefinedFunction: function gen_random_uuid() does not exist
HINT: No function matches given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Mythic/server.py", line 1, in <module>
	from app import (
  File "/Mythic/app/__init__.py", line 214, in <module>
    import app.api
  File "/Mythic/app/api/__init__.py", line 1, in <module>
    from app.api import callback_api, operator_api, task_api, response_api, crypto_api
  File "/Mythic/app/api/callback_api.py", line 4, in <module>
    from app.database_models.model import (
  File "/Myhic/app/database_models/model.py", line 3051, in <module>
    Operation.create_table(True)
  ...
peewee.ProgrammingError: function gen_random_uuid() does not exist
```

2. Issue with "ON CONFLICT"
After adding pgcrypto I am having following issue visible in mythic_postgres logs. I check this by running ./mythic-cli logs mythic_postgres
The error is:
```
ERROR:  syntax error at or near "ON" at character 85
STATEMENT:
            INSERT INTO hdb_catalog.hdb_version (version, upgraded_on) VALUES ($1, $@2)
            ON CONFLICT ((version IS NOT NULL))
            DO UPDATE SET version = $1, upgraded_on = $2
```

Similar error is visible in mythic_graphql and mythic_nginx. It seems postgres must be updated to 9.5.

**Comment by mike-t225** [comment]
Ok, I have figured out what is the problem and will close the ticket. I have downloaded mythic_postgres:0.0.2 once again. The one I had I downloaded some time ago and had postgres 9.4, I have downloaded it again and it has postgres 13. With this the problem doesn't occur.
