### ISSUE TITLE
Shell doesn't allow for followup inputs

### ISSUE THREAD

**Issue by cyber-ry** [its-a-feature/Mythic#190]
When running a shell command with runas, the shell returns with an input password for "user": but I am unable to input a response through the task.

**Comment by its-a-feature** [comment]
Is this for a specific agent? If so, I would suggest opening the issue against that agent's repository instead. 

For the more general case, Mythic doesn't currently support passing additional information to a task once it's been submitted. If you need an interactive aspect, the current recommended process is to use SOCKS

**Comment by cyber-ry** [comment]
It was specifically for Apollo so I can move this over there. I did attempt to use SOCKS and I wasn't having much success.

**Comment by its-a-feature** [comment]
Do you have specific information for what was going wrong with SOCKS? If you're using proxychains, make sure you specify SOCKS5 and not SOCKS4

**Comment by its-a-feature** [comment]
There's a new type of tasking that will allow for follow-on input with Mythic 3.1.0. We'll need to take some time to see the best way to add it for things like apollo, but poseidon has a new `pty` command that supports this.
