### ISSUE TITLE
Mythic Poseidon Generates Wrong Callback Host Path with HTTP C2 Profile

### ISSUE THREAD

**Issue by Greenwolf** [its-a-feature/Mythic#204]
When you generate a Poseidon Agent it wrongly appends to Callback Port to the end of the Callback Host.

When you use Apfell to specify a callback host it correctly appends the port to the end of the domain when using a path for redirection. 

For example if you use Apfell and set the Callback host to https://mydomain.com/mypath and the Callback Port to 443.

Then you have a redirector at this address passing it to port 80, it works correctly because it generates https://mydomain.com:443/mypath

If however you use Poseidon it generates it wrongly and becomes https://mydomain.com/mypath:443

You can see this in the output the binary generates.

```
myuser@myhost ~ % ./poseidon.bin
error client.Do: Post "https://mydomain.com/mypath:443/data": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
error resp.StatusCode: <nil>
^C
```

The poseidon payload should use the same code as the Apfell payload to correctly allow payload generation when specifying a URL path in the Callback Host parameter.

**Comment by its-a-feature** [comment]
Good catch! I'll look into making sure that the port number doesn't just get appended to the end. 

In the meantime, you can specify the `callback host` as `https://mydomain.com`, the `callback port` as `443`, and there's a separate parameter for the post URI, specify for that one to be `mypath`. With that setup, you should get `https://mydomain.com:443/mypath`.

**Comment by Greenwolf** [comment]
I changed the redirector to not bother with the paths for now, but I still have problems with Poseidon and none for Apfell.

I use exactly the same domain, port and redirector as the Apfell payload but get this error with Poseidon. 

```
 % ./poseidon-https-2.bin
error resp.StatusCode: <nil>
error resp.StatusCode: <nil>
error resp.StatusCode: <nil>
error resp.StatusCode: <nil>
```

I changed the GET and POST URI Parameters to index2 and data2 and then i stopped having problems. Is Mythic supposed to support overlap of POST/GET URI parameters between payloads or do they need to be unique? This could be a separate issue?

**Comment by Greenwolf** [comment]
Doing a little bit more testing around this issue and I believe it is also affecting the Websockets C2 profile too. 

When Poseidon uses websockets it is not as verbose in its errors:

```
2022/03/31 18:24:46 Error connecting to server websocket: bad handshake
2022/03/31 18:24:56 Error connecting to server websocket: bad handshake
```

When using the exact same nginx proxy settings, configured on the backend to pass to 8081 it doesn't work when using a location path.

However if i configure it without the path as the root on another port, but with the exact same proxy parameters, the websockets profile will work.

I've included some nginx snippets to show you what I mean:

This doesn't work (part of a larger config listening on 443 that works with Apfell+Poseidon HTTP), i think because of the same path issue above (but i'm including this here because i'm not sure if you need to fix it in the Poseidon Agent code, or in HTTP and Websockets code?) 
```
    location /websocket/ {
          proxy_pass http://internal_ip:8081;
          proxy_redirect off;
          proxy_ssl_verify off;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          # WebSocket support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
    }
```

While this will work with the Poseidon Websockets C2 Profile:
```
server {
    server_name mydomain.com;

    location / {
        proxy_pass http://internal_ip:8081;
        proxy_redirect off;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    listen 8081 ssl;
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Comment by its-a-feature** [comment]
I just made a push to the main branch for poseidon at `https://github.com/MythicAgents/poseidon` that should address these issues (same processing logic as the Apfell agent). You can update your poseidon install with `sudo ./mythic-cli install github https://github.com/MythicAgents/poseidon -f` then generate new agents.

**Comment by Greenwolf** [comment]
Hey @its-a-feature, I'm just testing this for you. On my end i'm seeing a problem with Websockets not starting on 8081. Digging down it seems to be mythic as we are not running anything else on that port. Perhaps an issue with the changes you pushed? 

![Screenshot 2022-04-02 at 20 36 46](https://user-images.githubusercontent.com/48361984/161392509-2d6111fd-faf4-4532-a369-282785b4ea4b.png)

```
user@mythic:~$ sudo netstat -antp | grep 8081
tcp6       0      0 :::8081                 :::*                    LISTEN      14034/server        
user@mythic:~$ sudo ps aux | grep 14034
root       14034  0.0  0.1 304976  4756 ?        Sl   Apr01   0:00 /Mythic/c2_code/server
user    129383  0.0  0.0   8168  2480 pts/0    S+   16:35   0:00 grep --color=auto 14034
```

**Comment by its-a-feature** [comment]
Did you figure out what was listening on that port? I can't seem to replicate this on a fresh install

**Comment by its-a-feature** [comment]
I think we solved the original issue - not sure if you ever figured out what was listening on port 8081 for you websocket, but if you have more information to report about it I can re-open and try to address that
