### ISSUE TITLE
Mythic Poseidon Missing Documentation for poseidon_tcp C2 Profile

### ISSUE THREAD

**Issue by Greenwolf** [its-a-feature/Mythic#205]
The Mythic Poseidon Agent is missing documentation for the poseidon_tcp C2 profile.

The lack of documentation can cause users to assume it functions as a reverse tcp payload, similar to metasploit, which is then confusing as there is no callback host parameter as seen in the below screenshot.

![Screenshot 2022-03-30 at 19 49 40](https://user-images.githubusercontent.com/48361984/160877121-bce8f949-fb82-45f8-871e-e18202280578.png)

Documentation should be updated to explain the P2P functionality in the generated Mythic Docs. 

P.S Thanks for all your hard work!

**Comment by Greenwolf** [comment]
Thanks Cody, my mistake here was only looking at the Mythic generated documentation, I couldn't find anything about poseidon_tcp agent here but I've found it in the website docs now. Shall I update this issue into a feature request for more info in the poseidon docs or close it?

P.S I did your course last year, but been so busy only just getting round to implementing Mythic into all our workflows!

**Comment by its-a-feature** [comment]
No worries! Yup, that would be great. I definitely need to include information in the poseidon documentation about it.

I'm glad you're getting a chance to check out Mythic!

**Comment by its-a-feature** [comment]
I just made a push to the main poseidon repo at `https://github.com/MythicAgents/poseidon` with updated documentation for the `poseidon_tcp` profile and the two new `link_tcp` and `unlink_tcp` commands.

**Comment by Greenwolf** [comment]
Looks fantastic! just updated and its really nice and clear. Thank you!
