### ISSUE TITLE
Feature Request: More Configurations from .env/config files - Global Webhooks + Operations

### ISSUE THREAD

**Issue by Greenwolf** [its-a-feature/Mythic#206]
It would be awesome if it was possible to create an operation and configure webhooks for it from configuration files or the Mythic .env file. 

As per here but just supplying the url and say a .txt file to get it all configured. 
https://docs.mythic-c2.net/v/version-2.2/operational-pieces/operations

The main use case is to make it easier to get a Mythic server configured and ready for an operation when using automated tooling such as Terraform and Ansible. 

For example:
WEBHOOK_URL=
WEBHOOK_BODY_FILE=
OPERATION_NAME=

**Comment by its-a-feature** [comment]
That's a good idea! I'll try to get that added into the next version update

**Comment by Greenwolf** [comment]
Thank you! Typical flow would be downloading Mythic, then moving an uploaded .env file from /tmp/ to Mythic/.env, then when it starts it would be great if it added any new config options to the existing file (for future updates).

So if our .env file is lacking new options you add it, it still works and just acts as a partial configuration.

**Comment by its-a-feature** [comment]
I think I'm going to do you one better for this. I'm working on the back-end rewrite and I'm going to create and entirely new docker container that'll handle nothing but webhooks. This way i can easily just emit more kinds of messages to that container and from the container, do any sort of processing and web networking as needed without bogging down the main server. So, this is a good time to start thinking about what _other_ kinds of webhooks you might want besides just new callbacks

**Comment by its-a-feature** [comment]
This is added in as of v3.0.0rc40
