### ISSUE TITLE
Arm64 / Mythic_CLI /etc 

### ISSUE THREAD

**Issue by necrose99** [its-a-feature/Mythic#207]
rpi4 might be usefull for a runner weight is far less ... and if you have an 8 gig pi/s laying about...
with apt , i lack room for server racks , 

ISSA / meetup.com CFT type deal-eos beats lugging a few dozen pounds of server or extra laptops... 

https://github.com/dsorm/gox  his fork has better platforms...  least in platforms.go 

Mythic_CLI  for windows builds nicely , need a few rpi 8 gigs .... as for redteam testing rpi4 4 gigs fall flat under xfce with xen/nmap  etc soon.  ie gentoo/pentoo xfce , 4 gigs with agressive gui tools will crash ...
ie add x86/kvm/quemu+ docker as a micro server likewise... 

windows 11 on arm64  Mythic_CLI_windows_arm64.exe , 

Amd64 Acronis Backup's  Malware detection  with brute-UPX hates on Mythic_CLI  Amd64 EXE hard , 386 seems to escape its scans.. 
for docker desktop wsl2 / kali runs ne way , so running dockers n Linux old hat anyways. 
ie PI minner / mit /pi coins etc runs docker on win/docker desktop as is. 

upx for darwin/Apple  Desktop os runs but for arm64 Mythic_CLI , ie Docker desktop ala mac... any thus mythic images etc. 

https://github.com/joshkunz/qemu-docker 

its not the greatest docker builder but its a hackish start..  gox/flgs  , while no docker expert ,  i chose the testing branch of debian bit less hassle in stale golang / gox 

[Mythic_CLI.Dockerfile.txt](https://github.com/its-a-feature/Mythic/files/8413533/Mythic_CLI.Dockerfile.txt)

anyway could have more platform runners of the cli i suppose.. 

![mythic-cli-via-gox](https://user-images.githubusercontent.com/2396239/161645792-f57e9b56-b13c-4292-b9ea-66119403dc14.png)
![mythic-cli-CMD_exe](https://user-images.githubusercontent.com/2396239/161646166-8dc389d6-c5d4-40d4-b37a-4761deeab5a7.png)

**Comment by its-a-feature** [comment]
Compiling mythic-cli into various other os/architecture combinations is fine, but there are bigger issues for Mythic as a whole to support ARM - the Docker containers for things like postgres, rabbitmq, graphql, etc would need to be updated (assuming they even have ARM compatible versions). It's currently not supported, but can be added to the roadmap if there's more desire for it
