### ISSUE TITLE
Callback Agent tablelist view is not properly visible

### ISSUE THREAD

**Issue by Monst3rSec** [its-a-feature/Mythic#212]
The callback agent flexible window is not properly visible whenever a new callback came( screenshot 1 ). I have temporarily fixed the issue by changing the height value ( screenshot 2 )

`<div style="flex-grow: 1; flex-basis: 30%; height: 50%;"> `

Kindly fix the issue in the main branch. 

**Screenshot 1:** 

![image](https://user-images.githubusercontent.com/60444051/163119392-4ef12e47-236e-4eae-9577-3d9ba3d51051.png)

**screenshot 2:**

![image](https://user-images.githubusercontent.com/60444051/163119609-4c3d6720-e7d6-4d21-bfd4-1b80d5d96ef5.png)

Thanks.

**Comment by its-a-feature** [comment]
What version of the UI are you using? If you click the hamburger icon in the top left there should be text at the bottom that gives a version number. I'm having trouble replicating it

**Comment by Monst3rSec** [comment]
Hi @its-a-feature ,

The UI Version number is v2.3.8. Please check the screenshot for reference. 

![image](https://user-images.githubusercontent.com/60444051/163927355-8409ffc8-a30b-4c8b-9993-4ae56a3fb197.png)

Thanks

**Comment by its-a-feature** [comment]
That's the Mythic version, there's a separate UI version at the bottom of that same panel. If you need to adjust the heights, it should all be based on percentages that you can change via that blue plus in the top right corner - the last option when you hover over it allows you to adjust the heights of the top and bottom piece in terms of percentages.

**Comment by Monst3rSec** [comment]
Thanks @its-a-feature, The UI Version is 0.0.44

**Comment by its-a-feature** [comment]
I'm going to close this for now, but if you experience this again please comment back here
