### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by bri5ee** [its-a-feature/Mythic#218]
I ran into some problems with Mythic running on an ARM chip. I went ahead and compiled the mythic-cli binary from the MythicMeta GitHub organization and all was well. However, when deploying the containers I received some errors. I assume this may be because the containers are Intel-based or that there may be some underlying issue internally to the container.
<img width="1661" alt="Screen Shot 2022-04-21 at 11 24 47 PM" src="https://user-images.githubusercontent.com/58535635/164616721-bce18ef7-21be-4dc8-9542-91531015f6bd.png">

<img width="533" alt="Screen Shot 2022-04-21 at 11 26 53 PM" src="https://user-images.githubusercontent.com/58535635/164616186-fd073137-ea35-4e94-952c-fcb8ac397d56.png">

Looking at the status of the containers I noticed 3 of the Mythic services weren't starting properly.
<img width="523" alt="Screen Shot 2022-03-01 at 3 21 20 PM" src="https://user-images.githubusercontent.com/58535635/164616079-f3584686-bd42-4a2e-9b30-5cfc5246bcf8.png">

If there is any known way to resolve this issue or if ARM is something that will be supported in the future I'd love to hear about it.

Thanks!

**Comment by necrose99** [comment]
As for cli thiers a fork of gox , that even dose riscv64..
Pull requests is still pending... this builds the mythic cli for more targets.. 
Anyway the goreleaser.yml could be added to build more via baked in github actions.. 

With odriod m1 8 gigs  , having petty boot, ie grub-aarch64.efi,  and it just boots like a pc..  replace rpi4 with 8.. gigs 250$/COVID/AWS gouging vs 75... and m1 has m.2 slot  built-in..

For capturing the flag , ie local owasp , issa shows, etc do able,  x86 could emu via qemu/docker.. or balena engine ie docker with emu tweeks.. 

Im shure thiers to rebuild mythic images , to local os somehow..

**Comment by its-a-feature** [comment]
Right now ARM isn't supported - it's a bigger question than just compiling the mythic-cli binary for ARM since a bunch of the Docker containers don't have ARM compatible versions. I can add it to the road map to eventually support it
