### ISSUE TITLE
DCSync output

### ISSUE THREAD

**Issue by chr0n1k** [its-a-feature/Mythic#219]
I was testing out the inbuilt commands and when running ```dcsync``` I noticed that the output of the command does not fully populate. I started with population of required fields to run dcsync as shown below:

![image](https://user-images.githubusercontent.com/30057970/165082341-dc2c6c86-679d-4fcb-9867-db5fbc90fb37.png)

After running ```dcsync``` I saw that the output ends after 15 lines as shown below:

![image](https://user-images.githubusercontent.com/30057970/165082529-2f2bf650-8a5d-4927-aad4-714367002856.png)

I tested using powershell-import to import the **Mimikatz** script and running dcync using powershell worked fine as shown below:

![image](https://user-images.githubusercontent.com/30057970/165082663-e060856f-2dbd-425e-88de-ad2e2fbc4128.png)

Any idea what could be causing this?

**Comment by its-a-feature** [comment]
hm... So, the new UI by default only displays 10 responses from the agent for any given task at a time. In that top example, when you click to expand the task, are there multiple pages at the bottom that you can click through?

**Comment by chr0n1k** [comment]
Expanding the task view still gives just those 15 lines:
![image](https://user-images.githubusercontent.com/30057970/165085387-a0553ff2-f554-458e-b602-6d5140d35e26.png)

**Comment by its-a-feature** [comment]
Does that same thing happen every time you run dcsync? what about other commands that also run `execute_pe`?

**Comment by chr0n1k** [comment]
Yea **dcsync** gives the same result every time. I tried registering Seatbelt and running it using the **execute_pe**:
![image](https://user-images.githubusercontent.com/30057970/165103770-d44f2a35-eeb1-46d4-b4fd-6e511ee5f566.png)

That resulted in a blank output (not sure if I did this the right way):
![image](https://user-images.githubusercontent.com/30057970/165104049-22fbc803-84da-44c2-bbb1-e99343fd3b18.png)

I also tried running **mimikatz** and leverage the dcsync module which spat out a lot more than 15 lines of error output:
![image](https://user-images.githubusercontent.com/30057970/165104765-cc463a59-fcb6-431c-9d86-d12a986ccdf3.png)

**Comment by djhohnstein** [comment]
As far as the `dcsync` stuff is concerned, I'd have to spin up my lab and retest. If you try something simple but with long output like `sekurlsa::logonpasswords`, do you get the same truncated output? 

For Seatbelt not working with `execute_pe`, that's intended. I classify .NET executables as "assemblies" so they'll be included with the "assembly" suite of commands. 

.NET Assembly Commands (from [here](https://github.com/MythicAgents/Apollo/blob/master/documentation-payload/apollo/commands/_index.md)):
- [inline_assembly](https://github.com/MythicAgents/Apollo/blob/master/agents/apollo/commands/inline_assembly)
- [execute_assembly](https://github.com/MythicAgents/Apollo/blob/master/agents/apollo/commands/execute_assembly)
- [assembly_inject](https://github.com/MythicAgents/Apollo/blob/master/agents/apollo/commands/assembly_inject)
- [register_assembly](https://github.com/MythicAgents/Apollo/blob/master/agents/apollo/commands/register_assembly)

`execute_pe` documentation:
- [execute_pe](https://github.com/MythicAgents/Apollo/blob/master/documentation-payload/apollo/commands/execute_pe.md)
- https://github.com/nettitude/RunPE

**Comment by chr0n1k** [comment]
Runnung ```sekurlsa::logonpasswords``` executed properly:

![image](https://user-images.githubusercontent.com/30057970/165155886-08599ef0-3c54-4de5-bec1-79a1272ac48b.png)

**Comment by djhohnstein** [comment]
Strange. I'll try and take a look but not sure what's happening. I know I used the `dcsync` module pretty recently with no issues. If I find something out I'll post here!

**Comment by chr0n1k** [comment]
I'll spin up another box and test. Will put up an update asap!

**Comment by chr0n1k** [comment]
Hi guys,

I created a fresh box with a clean install of Mythic and can confirm that ```dcysnc``` works. 

![image](https://user-images.githubusercontent.com/30057970/165393674-6259a291-6ac9-41ac-8b44-7afe0080c5bd.png)

I think it was an issue in my initial deployment.
