### ISSUE TITLE
Active Callbacks list should show if callback is sleeping/expected/overdue

### ISSUE THREAD

**Issue by ketumbra** [its-a-feature/Mythic#220]
Based on the last known sleep command, it should be trivial to calculate when the next checkin is expected. I would like to see some additional information to show this state. Possibly by color-coding the existing `last checkin` column.

- Black / waiting - check-in is not expected yet as agent should still be sleeping
- Yellow / expected - check-in window is now within configured jitter and is expected 
- Red / overdue - agent has not checked-in in expected interval

I'd be happy to help implement this feature if you could point me at the right parts of the code

Thanks

**Comment by its-a-feature** [comment]
Hey! 

I'd be happy to brainstorm how we could approach this. I think this is a _bit_ more complicated than you're anticipating though. The first thing if we want to calculate it though is to identify and solidify a standard format. Some agents have "working hours" which might indicate that they only checkin between 9-5 M-F with some jitter/sleep within that. Some agents just have sleep/jitter, some (like the Merlin agent) use additional skew parameters. With all of the variations, it's hard to say when the agent should have connected in within some range. 

Right now a callback as a field called "sleep_info" which is free-form. If we can identify a standard structure to capture all this sort of information, then we can use that to track the results of adjusting sleep intervals in the database and then adjust the color in the UI like you're suggesting. 

Currently, in the new UI if you right click the table header on the active callbacks page, there's a column you can opt to show for sleep info which just shows a blue alarm clock if sleep info has been set and an orange one if sleep info hasn't been set.

**Comment by its-a-feature** [comment]
Happy to re-open this issue if you have ideas about how to approach the variety in agent sleep patterns
