### ISSUE TITLE
Uninstall Mythic?

### ISSUE THREAD

**Issue by MavericksGooses** [its-a-feature/Mythic#232]
How can I uninstall Mythic with Merlin? I have several others servers and evidently Mythic is preventing them from running using some of the same ports. How do I remove?

**Comment by its-a-feature** [comment]
Hi! If you want to stop mythic to prevent it from using the same ports as other services, you can stop it with `sudo ./mythic-cli stop` - that'll stop all of the containers and remove them (the images will still exist on the system though). If you want to keep running Mythic but just change the ports that the Mythic services use, look at the `Mythic/.env` file for the ports that are being used, change them to something else, and then restart Mythic `sudo ./mythic-cli restart` - that'll bring Mythic back up using the changed ports.
