### ISSUE TITLE
Unable to Create an Apollo Payload

### ISSUE THREAD

**Issue by bkndBrackets** [its-a-feature/Mythic#242]
Trying to build an apollo.exe payload with an HTTP C2 and getting the following error. (Ps. apfell.js payload are built successfully using HTTP C2 profile) 

![Screenshot from 2022-07-26 22-34-29](https://user-images.githubusercontent.com/50724723/181148329-950b8424-d247-4437-9dc1-5468c34397a0.png)

**Comment by bkndBrackets** [comment]
Which container exactly?

I checked apollo's container and it can indeed reach the internet.

![Screenshot from 2022-07-28 18-10-55](https://user-images.githubusercontent.com/50724723/181646054-49bf1fad-d1dd-4ab9-9775-a61976c0727c.png)

![Screenshot from 2022-07-28 18-12-59](https://user-images.githubusercontent.com/50724723/181646183-4dff5d65-9cec-41e1-932b-222d31b23a20.png)

Weird that I can build a an apfell.js successfully, but not apollo's.

Interestingly enough, I tried to manually wget the Fody package itself from within the container, and it just hangs after starting to download. 

![Screenshot from 2022-07-28 18-23-22](https://user-images.githubusercontent.com/50724723/181647419-5115731e-0b61-4e9c-8130-c958a64e0c9a.png)

**Comment by its-a-feature** [comment]
hm.. maybe it's an issue with the Fody package? The apfell payload is just javascript, so it's not trying to reach out and pull down packages like the Apollo payload is, that's why there's the difference. Whatever is causing that fody download within the container is the source of the problem for why you can't build the apollo payload.

For what it's worth, looks like I'm also having that issue:
```
Restoring NuGet package Fody.2.0.0.
WARNING: Unable to find version '1.6.2' of package 'Costura.Fody'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  No such host is known

WARNING: Unable to find version '2.0.0' of package 'Fody'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  No such host is known

WARNING: Unable to find version '1.6.2' of package 'Costura.Fody'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  No such host is known

WARNING: Unable to find version '2.0.0' of package 'Fody'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  No such host is known
```
I'd suggest opening up an issue against that specific agent's repo so they can track down what's up

**Comment by bkndBrackets** [comment]
I will... so the manual download took (wget) took ~30mins to finish (absurd amount of time) given that the Fody package is ~290K.  

According to the output a System.TimeoutException exception is thrown after no "data is received for 60000ms". So that makes kinda sense...

Although, I wonder if their a way to manually onfigure the source code that pulls the Fody package to not throw the Timeout exception after 60000ms?

![Screenshot from 2022-07-28 22-18-17](https://user-images.githubusercontent.com/50724723/181669971-0e0a7768-03ed-4735-a6c6-6e0242b44b83.png)

**Comment by Laransec** [comment]
> hm... that looks like it might be an issue with the Docker container being able to reach the internet? Can you confirm that the containers can reach the internet?
 
So we have a situation where we are unable to Nuget packages.  Is there any way to get the container to keep these resources around statically instead of pulling them down each time

**Comment by its-a-feature** [comment]
As part of the build command that runs it refreshes the Nuget packages. You should be able to build once in a normal environment and move the container over, or since you have some internet access, but it's SUPER slow, you can just edit the build command line to not refetch every time. Once it's pulled down once and that part of the command line is removed, it should be fine, even after reboot.

you could also potentially add those nuget fetches as part of the Dockerfile itself via `RUN` commands.

**Comment by its-a-feature** [comment]
Thanks to the @spicybyte user on the bloodhound slack, here are some instructions for doing offline builds for all agents, and specifically for Apollo

# Apollo Offline Installation 

Note: This guide will assume you can install Mythic on a box that has Internet access and then migrate to your offline testing/development environment. 

## Setup 

1. Install Mythic following the [Mythic Installation guide](https://docs.mythic-c2.net/installation).


2. With Mythic running, install Apollo along with any other agents or profiles you might need/want.
```
sudo ./mythic-cli install github https://github.com/MythicAgents/Apollo
```

3. Export your docker containers. Make sure you also save the tags.
```
docker save $(docker images -q) -o mythic_images.tar
docker images | sed '1d' | awk '{print $1 " " $2 " " $3}' > mythic_tags
```

4. Download donut from pypi. (this is apollo specific)
```
mkdir Payload_Types/apollo/depends
pip3 download donut -d Payload_Types/apollo/depends
```

5. Download Apollo dependencies.
```
 wget https://www.nuget.org/api/v2/package/Fody/2.0.0 -O Payload_Types/apollo/depends/fody.2.0.0.nupkg
 wget https://www.nuget.org/api/v2/package/Costura.Fody/1.6.2 -O Payload_Types/apollo/depends/costura.fody.1.6.2.nupkg
 ```

6. Tar Mythic directoy.
```
tar cfz mythic.tar.gz /Mythic
```

5. Push `mythic_images.tar`, `mythic_tags`, and `mythic.tar.gz` to your offline box.


6. Import docker images and restore tags. 
```
docker load -i mythic_images.tar
while read REPOSITORY TAG IMAGE_ID; do echo "== Tagging $REPOSITORY $TAG $IMAGE_ID =="; docker tag "$IMAGE_ID" "$REPOSITORY:$TAG"; done < mythic_tags
```

7. Extrac Mythic directory.
```
tar xfz mythic.tar.gz
cd mythic
```

8. Update Apollo's Dockerfile (at the time of use, it might not be 0.1.1 anymore, check for the latest)
```
> cat Payload_Types/apollo/Dockerfile
from itsafeaturemythic/csharp_payload:0.1.1

COPY ["depends/donut-0.2.2.tar.gz", "donut-0.2.2.tar.gz"]
COPY ["depends/costura.fody.1.6.2.nupkg", "costura.fody.1.6.2.nupkg"]
COPY ["depends/fody.2.0.0.nupkg", "fody.2.0.0.nupkg"]

RUN /usr/local/bin/python3.8 -m pip install /donut-0.2.2.tar.gz
RUN mkdir /mythic_nuget
RUN nuget sources add -name mythic_nuget -source /mythic_nuget
RUN nuget sources disable -name nuget.org
RUN nuget add /fody.2.0.0.nupkg -source /mythic_nuget
RUN nuget add /costura.fody.1.6.2.nupkg -source /mythic_nuget
```

9. Start Mythic/Apollo
```
sudo ./mythic-cli start
