### ISSUE TITLE
Golang API

### ISSUE THREAD

**Issue by Techno-Fox** [its-a-feature/Mythic#243]
I've read a comment of yours stating that your were in the process of reprogramming the back end into golang, if that is the case, then will there a Golang API  for scripting (Not creating agents, poseidon has a really good code base for that if you want to make your own.) like there is in python? I ask this because I would like to make a TUI of Mythic (Some may consider this redundant, but there are use cases, such as ssh, and text based only systems, also personal preference). 

I would like to make this in Golang, so that it may be easily portable, fast, and all in one binary. I just wanted to ask if an Golang API for Mythic is or will be in the works?

**Comment by its-a-feature** [comment]
Great question! I haven't considered making a Golang Scripting API, but it wouldn't be hard. The new scripting (currently available in the PyPi version 0.0.37) mainly hits the GraphQL back-end and returns data (https://github.com/MythicMeta/Mythic_Scripting/blob/master/mythic/mythic.py). 99% of the functions I have in there are simply "helper" functions to get users going without having to write their own GraphQL queries. If you're wanting to make your own Terminal UI, then it would probably be most beneficial to simply fetch the data that you need and nothing else (which is what GraphQL excels at). GraphQL is simply a structured input/output format with normal HTTP POST messages (and websockets if you want to stream data). 

If you're curious about testing out some custom GraphQL stuff, then in your Mythic instance browse to `https://mythicIP:7443/console` and you'll see the Hasura login page. The secret it wants will be in your `Mythic/.env` file as `HASURA_SECRET`. From there, you'll be brought to the API page where you can craft and test your own queries/mutations/subscriptions right there to see exactly what data you get back. 

If you wanted to take the first stab at even making a simple Golang Library to log into Mythic and provide custom queries/subscriptions, I'd be happy to review and collaborate :)
The code for doing basic gets/post/queries/subscriptions for the current scripting is here: https://github.com/MythicMeta/Mythic_Scripting/blob/master/mythic/mythic_utilities.py. 
A list of all the basic queries are here: https://github.com/MythicMeta/Mythic_Scripting/blob/master/mythic/graphql_queries.py.

If you want to see from the UI perspective what exactly is getting called to fetch/update certain things, https://github.com/MythicMeta/MythicReactUI/tree/main/src/components/pages has all the pages and their React source (generally the query/mutations will be outlined at the top of the pages).

**Comment by Techno-Fox** [comment]
I'll definitely take a Crack at it. I'll start with the API and see if you all like it. Due to work, I don't know the eta, but I can provide updates. If needed. Where would I provided progress updates?

**Comment by its-a-feature** [comment]
Awesome! No worries on the ETA :) Um... If you wanted to open an issue/running PR for the `https://github.com/MythicMeta/Mythic_Scripting` repo, that would be perfect. That way we can keep all of that code in one place.

**Comment by Techno-Fox** [comment]
I've opened an issue at https://github.com/MythicMeta/Mythic_Scripting
