### ISSUE TITLE
Error getting json from server 

### ISSUE THREAD

**Issue by Chizzy4u** [its-a-feature/Mythic#244]
Am having issues login into the ui ..error getting json from server ..I keep getting that each time I try to login ..how can I solve this issues.

**Comment by its-a-feature** [comment]
Hi! Can you go to the Mythic server and run `sudo ./mythic-cli logs mythic_server` and share the output? It sounds like there's some sort of error with communicating between the UI and the server

**Comment by Chizzy4u** [comment]
Each time I login it logs me out and says failed to connect to mythic server ..I reinstalled from the previous one but still I keep getting kicked out ..

**Comment by its-a-feature** [comment]
In order to see what's going on, i need you to ssh into the computer running Mythic and run `sudo ./mythic-cli logs mythic_server` so i can try to see what the error is. it would also be helpful to see `sudo ./mythic-cli status`

**Comment by its-a-feature** [comment]
Any additional details or progress on this one?

**Comment by its-a-feature** [comment]
Closing this one due to lack of information

**Comment by Art-Fakt** [comment]
Hi I have the same error when I'm trying to connect to the Web-UI. Here is my output from sudo ./mythic-cli logs mythic_server, it seems my authentification with my user to thepostgre db fails.

the output :
{"level":"error","error":"pq: password authentication failed for user \"mythic_user\"","func":"github.com/its-a-feature/Mythic/database.getNewDbConnection","line":122,"host":"mythic_postgres","port":5432,"time":"2023-06-11T18:05:47Z","message":"Failed to connect to database"}
