### ISSUE TITLE
Feature Request: Interactive Tasks

### ISSUE THREAD

**Issue by DarkC0ntributor** [its-a-feature/Mythic#246]
It would be great to be able to add data to task after it has been submitted.
E.g. to provide a STDIN to `cmd`/`powershell`/...

The Agent side looks like it is already possible.
However, UI and API don't allow this.

This would be the Mythic part of #190

**Comment by jakebacker** [comment]
+1ing this issue. Being able to use an interactive shell would be great. It definitely seems like it'd need new UI though.

**Comment by its-a-feature** [comment]
This is now added to the Mythic 3.1.0 release!
