### ISSUE TITLE
Unable to get callback from remote system

### ISSUE THREAD

**Issue by samy4samy** [its-a-feature/Mythic#248]
Hi
managed to set it up and execute the payloads on the remote system however I'm unable to get the call back. (im using http profile with apfell ) : 

- Mythic version : 2.3.11
- i've added those MYTHIC_HOST to conf file .env to point to my public IP , same for WEBSOCKET : 
-
![myt1](https://user-images.githubusercontent.com/103023609/186859942-a14eeb32-6c7e-4783-ab15-322bdf89a8df.png)
![myt2](https://user-images.githubusercontent.com/103023609/186859952-de016132-ae02-45a5-b267-624f018c9067.png)

thx for your support

**Comment by its-a-feature** [comment]
Hey! The variables in the `.env` file configure how Mythic itself is configured, not how agents or c2 profiles are configured. Are you trying to have your agent call back directly to the `http` c2 profile or are you using a redirector? 

On the payloads page, you should be able to click the "Actions" button and then "Check Agent C2 Configuration" - this will send your agent configuration down to the c2 profile and check to see if there are any potential issues with it calling back. If there are issues, it should call them out. One additional thing to note about the apfell agent specifically is that it can't connect to self signed certificates.

**Comment by samy4samy** [comment]
Hey,
- yes I'm trying agent call back directly to the HTTP c2 profile.
- i clicked on "Check Agent C2 Configuration"  : seems there is no issue  === > "C2 profile container and agent configuration match port 80, and SSL expectations" .
-since in the payload generation :  i intentionally put in the Callbakc Host parameter : http://MyPublicIP  ( http and NOT https ) to avoid the issue of self signed certificates  ... or perhaps I'm doing something wrong  / or miss understanding.
regards.

**Comment by its-a-feature** [comment]
hm.. that all looks good then. From that target box, can you do `curl http://MyPublicIP`? you should see a warning notification appear in the Mythic UI (just trying to test to make sure that connectivity works).

**Comment by samy4samy** [comment]
i just found the issue ( thank you for the hint )  :+1:  
its was the Ubuntu fw  :(  === > ufw status  -- ufw allow 80   FTW 
you can close the issue, and once again thank you for support :+1:

**Comment by its-a-feature** [comment]
Ah, glad you were able to find it!
