### ISSUE TITLE
Just curious about Tasking

### ISSUE THREAD

**Issue by Techno-Fox** [its-a-feature/Mythic#251]
So while writing some structs to communicate with Mythic, I had a question of what would happen if you sent a response without a task id. How would mythic show that output, or response?

Example:
  You have an agent with a predefined action, this can be anything. Let's call it function X. You want to run X right after check in, however, Mythic didn't task the agent, because the agent already knew what it was going to do, thus no tracking id is given. So when X sends a response without a task id, how does Mythic output the response, if any?

I could be thinking about this completely wrong, so please correct me if I am.

**Comment by its-a-feature** [comment]
Hey! Great question. 

If you send a response without a taskID, then Mythic doesn't know what to do with the data, so it'll return back `{"status": "error"}`, put more data in an error log, and ignore the output. 

Normally, I'd say you'd have a script or something running that sees the moment you get a new callback that it automatically tasks X. I'm curious though, if an agent sent back a response that didn't match any task, what would you _expect_ Mythic to do? Or, where would you go to look for that sort of output?

**Comment by Techno-Fox** [comment]
Well, when the agent checks in they are given an ID from mythic or if not just used the UUID it is compiled with, then that is prepended to every message sent, I would think mythic would display the response of the message in a response box without a title. 

Essentially I though Mythic would get the message, see the UUID, know what agent it's for, but not know the task, so just put the output in a task less box.

**Comment by Techno-Fox** [comment]
I would say a place to look is artifacts, but well that's for artifacts, though I guess depending on function X that is where I would look, depending if it's files, or key logs, etc. I guess I would look where I would expected the output of X to be.

**Comment by its-a-feature** [comment]
ah, that's currently not possible. Those boxes that you see are streamed from the database based on the tasks you've issued and the responses are associated with those tasks. So, if there's no task, there's nothing to fetch from the database, so there's nothing for you to see in the UI. 

However, I could potentially do something like `help` and `clear` since those aren't actual agent commands. 

I want to get the scenario right though - would this same issue be solved if there was a way to automatically issue tasking when a certain payload checkins in for the first time?

**Comment by Techno-Fox** [comment]
Yea, I could see automatic tasking being done, that would also allow for different task to be assigned automatically if needed. However another to worry about is reboots, though if it's getting that command/tasking every time it checks in, that should be fine. 

I was just thinking about the scenario, and how Mythic would handle it. I was creating structs and the thought hit me.

**Comment by its-a-feature** [comment]
Well with a reboot, your agent would die and you'd get a new callback. So, your new callback would get those same tasks automatically issued.

If you think that would solve the scenario you're thinking of, then i'll chock it up to another request for that feature lol.

**Comment by Techno-Fox** [comment]
Yea, alright. Probably would be good to add. Sorry for the bother. I was just curious about a hypothetical scenario.
