### ISSUE TITLE
Rabbitmq channel overflow

### ISSUE THREAD

**Issue by Techno-Fox** [its-a-feature/Mythic#254]
Hello, I've come to annoy you again (I hope i don't)

I was working on a builder for an agent, I decided to add a debug mode (for testing the agent). This came out at 130MB (I know thats big, it's just debug info, when release compile and striped its 2MB to 4MB). Curiously I was getting a channel error from reading the builder payload into rabbitmq, i discovered that this was caused because rabbitmq has a message size limit, and the max being 512MB (536870912 bytes).

The error:

```
[*] Setting hostname (which should match payload type name exactly) to: <agentname>
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[*] Trying to connect to rabbitmq at: mythic_rabbitmq:5672
[+] Ready to go!
[*] mythic_service - Waiting for messages in mythic_service with version 12.
[*] mythic_service - total instances of scaredfox container running: 1
Reject is not sent since channel is closed
Exception in callback _task_done(<Task cancell...rvice.py:122>>) at /usr/local/lib/python3.8/dist-packages/aio_pika/tools.py:40
handle: <Handle _task_done(<Task cancell...rvice.py:122>>) at /usr/local/lib/python3.8/dist-packages/aio_pika/tools.py:40>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/aio_pika/tools.py", line 41, in _task_done
    exc = future.exception()
asyncio.exceptions.CancelledError
```

Now I know it's insane to think of an agent taking 512MB, but the default can be changed in rabbitmq-docker/rabbitmq.conf 

add the line

```
max_message_size = 536870911
```
This is the max, just adding 1 more byte will cause rabbitmq to crash. 

With all that, is there anyway to implement loading the payload in chunks? Or is this yet, another feature request.

**Comment by its-a-feature** [comment]
Hey! Yup, somebody else brought that up and I could have sworn I added something to help it, but I can't seem to find the code for it. The initial idea is to have a POST request and send the payload bytes back to Mythic that way instead of via the rabbimq message. The plan is to wrap that functionality behind the scenes so that you as the dev never have to check the size to see if you should send it back via POST or via rabbimq.

**Comment by its-a-feature** [comment]
With the new v3.0.0 version coming out in a few weeks I'm going to close this issue as it involved a completely different back-end system (switch from Python to GoLang). If you still encounter this issue with the new v3.0.0 code, we can re-open it
