### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by ghost** [its-a-feature/Mythic#260]
Currently there is no support for IPv6, and because `mythic-cli` is overwriting the `docker-compose.yml` and deleting the network `mythic_default_network` if it already exists it's nearly impossible to configure this. 

My request is to implement the possibility to use IPv6 or the possibility to overwrite the the default network configuration either by not deleting the `mythic_default_network` if it already exists or with configuration in `.env`.

**Comment by gso-trifork-security** [comment]
Adding IPv6 subnet

**Comment by its-a-feature** [comment]
In the `ipam.config.subnet` section? are you trying to replace it or make it an array?

**Comment by its-a-feature** [comment]
ok, just updated the `mythic-cli` binary to version 0.0.8 which should largely leave that `networks` section alone if it already exists
