### ISSUE TITLE
Feature Request: Webshell support

### ISSUE THREAD

**Issue by blitztide** [its-a-feature/Mythic#263]
I would like to propose adding webshell support, having aunified interface to allow commands to be sent would be fantastic.

It would probably need a new tab to be created to support outgoing connections, and OpSec considerations as you don't want direct webshell traffic from the C2 server.

**Comment by its-a-feature** [comment]
Hey! This was in the old UI and I added it back in for Mythic 3.0.0 support. After you create your payload, there's an option on the payloads page dropdown to create a callback based on that payload (without actually needing the agent to checkin with Mythic). At that point, you can use your agent container (or c2 profile container) do actually facilitate comms. So, the general flow would be:

Operator --> payload container --> webshell tasking
or
Operator --> payload container --> c2 profile container --> webshell tasking

I'll get some docs added for how that sort of thing would work
