### ISSUE TITLE
An error is reported when generating the openbsd arm payload

### ISSUE THREAD

**Issue by SeeNanshaneisurely** [its-a-feature/Mythic#266]
hello!
Using the mythical merlin module,An error is reported when generating the openbsd arm payload,How to solve

![1](https://user-images.githubusercontent.com/57738442/222028936-ce9d8f3c-7148-4649-817e-c15564c93932.png)

**Comment by its-a-feature** [comment]
I believe this was opened up against the Merlin repo as well and fixed, so I'll close it here too

**Comment by SeeNanshaneisurely** [comment]
Ok, thank you.
