### ISSUE TITLE
404 error trying to connect to Web UI Mythic 3.0

### ISSUE THREAD

**Issue by skinnypuppy** [its-a-feature/Mythic#270]
Installed Mythic 3.0 on latest Kali. No install issues, sudo mythic-cli status shows this :

MYTHIC SERVICE          WEB ADDRESS             BOUND LOCALLY
Nginx (Mythic Web UI)   https://127.0.0.1:7443   false
Mythic Backend Server   http://127.0.0.1:17443   true
Hasura GraphQL Console  http://127.0.0.1:8080    true
Jupyter Console         http://127.0.0.1:8888    true
Internal Documentation  http://127.0.0.1:8090    true

ADDITIONAL SERVICES     IP                      PORT    BOUND LOCALLY
Postgres Database       127.0.0.1               5432     true
React Server            127.0.0.1               3000     true
RabbitMQ                127.0.0.1               5672     true

Mythic Main Services
CONTAINER NAME          STATE           STATUS                          PORTS
mythic_documentation    running         Up 18 minutes (healthy)         8090/tcp -> 127.0.0.1:8090
mythic_graphql          running         Up 17 minutes (healthy)         8080/tcp -> 127.0.0.1:8080
mythic_jupyter          running         Up 17 minutes (healthy)         8888/tcp -> 127.0.0.1:8888
mythic_nginx            running         Up 17 minutes (healthy)         7443/tcp -> :::7443, 7443
mythic_postgres         running         Up 17 minutes (healthy)         5432/tcp -> 127.0.0.1:5432
mythic_rabbitmq         running         Up 17 minutes (healthy)         5672/tcp -> 127.0.0.1:5672
mythic_react            running         Up 17 minutes (healthy)         3000/tcp -> 127.0.0.1:3000
mythic_server           running         Up 18 minutes (healthy)         7000/tcp -> :::7000, 7001/tcp -> :::7001, 7002/tcp -> :::7002, 7003/tcp -> :::7003, 7004/tcp -> :::7004, 7005/tcp -> :::7005, 7006/tcp -> :::7006, 7007/tcp -> :::7007, 7008/tcp -> :::7008, 7009/tcp -> :::7009, 7010/tcp -> :::7010, 17443/tcp -> 127.0.0.1:17443, 17444/tcp -> 127.0.0.1:17444, 7000, 7001, 7002, 7003, 7004, 7005, 7006, 7007, 7008, 7009, 7010

Installed Services
CONTAINER NAME  STATE           STATUS          PORTS
apfell          running         Up 18 minutes
http            running         Up 18 minutes

[*] RabbitMQ is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
    Use 'sudo ./mythic-cli config set rabbitmq_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
[*] If you are using a remote PayloadType or C2Profile, they will need certain environment variables to properly connect to Mythic.
    Use 'sudo ./mythic-cli config service' for easy-to-use configs for these services.

I tried to navigate to the webUI via Firefox-esr and Chromium but get a '404 not found nginx 1.21.4'
Docker version is: $ docker --version
Docker version 20.10.23+dfsg1, build 7155243

I can actually get into the Hasura console but not the mythic webui.

Output from mythic-cli nginix log:

sudo ./mythic-cli logs mythic_nginx
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/services.conf.template to /etc/nginx/conf.d/services.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
127.0.0.1 - - [12/Mar/2023:22:25:16 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:25:48 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:26:19 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:26:20 +0000] "GET / HTTP/1.1" 301 169 "-" "Go-http-client/1.1" "-"
172.100.0.1 - - [12/Mar/2023:22:26:20 +0000] "GET /new/login HTTP/1.1" 404 153 "https://127.0.0.1:7443" "Go-http-client/1.1" "-"
127.0.0.1 - - [12/Mar/2023:22:26:50 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:27:18 +0000] "GET /new/login HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
172.100.0.1 - - [12/Mar/2023:22:27:19 +0000] "GET /favicon.ico HTTP/1.1" 404 18 "https://127.0.0.1:7443/new/login" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
127.0.0.1 - - [12/Mar/2023:22:27:20 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:27:36 +0000] "GET /new/login HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
127.0.0.1 - - [12/Mar/2023:22:27:51 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:28:21 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:28:51 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:29:22 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:29:52 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:30:23 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:30:53 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:31:23 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:31:54 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:32:11 +0000] "GET /new/login HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
172.100.0.1 - - [12/Mar/2023:22:32:11 +0000] "GET /favicon.ico HTTP/1.1" 404 18 "https://127.0.0.1:7443/new/login" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
127.0.0.1 - - [12/Mar/2023:22:32:24 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:32:54 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:33:25 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:33:55 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:33:56 +0000] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
172.100.0.1 - - [12/Mar/2023:22:33:56 +0000] "GET /new/login HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
172.100.0.1 - - [12/Mar/2023:22:33:57 +0000] "GET /favicon.ico HTTP/1.1" 404 18 "https://127.0.0.1:7443/new/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [12/Mar/2023:22:34:25 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:34:29 +0000] "GET /new/login HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
172.100.0.1 - - [12/Mar/2023:22:34:30 +0000] "GET /new/login HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
172.100.0.1 - - [12/Mar/2023:22:34:31 +0000] "GET /new/login HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
172.100.0.1 - - [12/Mar/2023:22:34:52 +0000] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
172.100.0.1 - - [12/Mar/2023:22:34:53 +0000] "GET /new/login HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [12/Mar/2023:22:34:56 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:35:22 +0000] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
172.100.0.1 - - [12/Mar/2023:22:35:22 +0000] "GET /new/login HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [12/Mar/2023:22:35:26 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:35:56 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:36:03 +0000] "GET /new/login HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
172.100.0.1 - - [12/Mar/2023:22:36:03 +0000] "GET /favicon.ico HTTP/1.1" 499 0 "https://127.0.0.1:7443/new/login" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
172.100.0.1 - - [12/Mar/2023:22:36:14 +0000] "GET /new/login HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
127.0.0.1 - - [12/Mar/2023:22:36:27 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:36:57 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:37:28 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:37:59 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:38:29 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:39:00 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:39:31 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:40:01 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:40:31 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:41:02 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:41:32 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:42:03 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:42:33 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:43:03 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:43:34 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:44:04 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:44:34 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:45:04 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:45:35 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
172.100.0.1 - - [12/Mar/2023:22:45:46 +0000] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
172.100.0.1 - - [12/Mar/2023:22:45:46 +0000] "GET /new/login HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
172.100.0.1 - - [12/Mar/2023:22:45:46 +0000] "GET /favicon.ico HTTP/1.1" 404 18 "https://127.0.0.1:7443/new/login" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
127.0.0.1 - - [12/Mar/2023:22:46:05 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:46:35 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:47:05 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:47:36 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:48:06 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:48:36 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:49:07 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:49:37 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:50:07 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"
127.0.0.1 - - [12/Mar/2023:22:50:37 +0000] "GET / HTTP/1.1" 301 169 "-" "curl/7.87.0" "-"

I don't know where to go from here?

**Comment by its-a-feature** [comment]
what's the output of `sudo ./mythic-cli logs mythic_server`? Also, what version of docker-compose do you have? Can you output the result of `sudo ./mythic-cli status` again?

**Comment by skinnypuppy** [comment]
Output from sudo ./mythic-cli logs mythic_server:

┌──(hacker㉿kali)-[~/extra/Mythic-3.0.0]
└─$ sudo ./mythic-cli logs mythic_server
[sudo] password for hacker: 
Step 1/6 - Initializing utilities
Step 2/6 - Initializing logging
Step 3/6 - Initializing database
{"level":"error","error":"dial tcp 172.100.0.5:5432: connect: connection refused","func":"github.com/its-a-feature/Mythic/database.getNewDbConnection","line":122,"host":"mythic_postgres","port":5432,"time":"2023-03-31T18:42:52Z","message":"Failed to connect to database"}
Step 3.5/6 - Initializing MITRE ATT&CK
Step 4/6 - Initializing webserver
Step 5/6 - Initializing rabbitmq
{"level":"error","error":"dial tcp 172.100.0.2:5672: connect: connection refused","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).GetConnection","line":126,"time":"2023-03-31T18:43:00Z","message":"Failed to connect to rabbitmq"}
Step 6/6 - Starting webserver
{"level":"error","error":"Failed to deliver message to exchange/queue. Error code: 0, Error Text: ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendMessage","line":189,"errorCode":0,"errorText":"","time":"2023-03-31T18:43:35Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"Failed to deliver message to exchange/queue. Error code: 0, Error Text: ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).EmitWebhookMessage","line":60,"time":"2023-03-31T18:43:35Z","message":"Failed to emit webhook Message"}

And from sudo ./mythic-cli status: 

┌──(hacker㉿kali)-[~/extra/Mythic-3.0.0]
└─$ sudo ./mythic-cli status            
MYTHIC SERVICE          WEB ADDRESS             BOUND LOCALLY
Nginx (Mythic Web UI)   https://127.0.0.1:7443   false
Mythic Backend Server   http://127.0.0.1:17443   true
Hasura GraphQL Console  http://127.0.0.1:8080    true
Jupyter Console         http://127.0.0.1:8888    true
Internal Documentation  http://127.0.0.1:8090    true

ADDITIONAL SERVICES     IP                      PORT    BOUND LOCALLY
Postgres Database       127.0.0.1               5432     true
React Server            127.0.0.1               3000     true
RabbitMQ                127.0.0.1               5672     true


Mythic Main Services
CONTAINER NAME          STATE           STATUS                          PORTS
mythic_documentation    running         Up 10 minutes (healthy)         8090/tcp -> 127.0.0.1:8090
mythic_graphql          running         Up 9 minutes (healthy)          8080/tcp -> 127.0.0.1:8080
mythic_jupyter          running         Up 10 minutes (healthy)         8888/tcp -> 127.0.0.1:8888
mythic_nginx            running         Up 10 minutes (healthy)         7443/tcp -> :::7443, 7443
mythic_postgres         running         Up 10 minutes (healthy)         5432/tcp -> 127.0.0.1:5432
mythic_rabbitmq         running         Up 10 minutes (healthy)         5672/tcp -> 127.0.0.1:5672
mythic_react            running         Up 10 minutes (healthy)         3000/tcp -> 127.0.0.1:3000
mythic_server           running         Up 10 minutes (healthy)         7000/tcp -> :::7000, 7001/tcp -> :::7001, 7002/tcp -> :::7002, 7003/tcp -> :::7003, 7004/tcp -> :::7004, 7005/tcp -> :::7005, 7006/tcp -> :::7006, 7007/tcp -> :::7007, 7008/tcp -> :::7008, 7009/tcp -> :::7009, 7010/tcp -> :::7010, 17443/tcp -> 127.0.0.1:17443, 17444/tcp -> 127.0.0.1:17444, 7000, 7001, 7002, 7003, 7004, 7005, 7006, 7007, 7008, 7009, 7010

Installed Services
CONTAINER NAME  STATE   STATUS  PORTS

[*] There are no services installed
    To install one, use "sudo ./mythic-cli install github <url>"
    Agents can be found at: https://github.com/MythicAgents
    C2 Profiles can be found at: https://github.com/MythicC2Profiles

[*] RabbitMQ is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
    Use 'sudo ./mythic-cli config set rabbitmq_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
[*] If you are using a remote PayloadType or C2Profile, they will need certain environment variables to properly connect to Mythic.
    Use 'sudo ./mythic-cli config service' for easy-to-use configs for these services.

**Comment by skinnypuppy** [comment]
Docker compose version is:
┌──(hacker㉿kali)-[~]
└─$ sudo docker-compose version
[sudo] password for hacker: 
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.11.2
OpenSSL version: OpenSSL 3.0.8 7 Feb 2023

**Comment by skinnypuppy** [comment]
Please close. Re-installed Kali due to ssd upgrade, re-installed Mythic 3.0 and all is working correctly.
