### ISSUE TITLE
SSO Support

### ISSUE THREAD

**Issue by runesage** [its-a-feature/Mythic#273]
It would be quite handy for larger engagements/teams to be able to use existing SSO ecosystems using OAuth/SAML rather than have to create accounts for everyone manually. This is something that could really make QOL easier on maintaining mythic deployments and flexible account management.

Current use case is I have a team that uses a self-hosted gitlab/mattermost instance and tying everything together would make the team more agile with account management.

**Comment by its-a-feature** [comment]
Somebody else asked about that too - it's something I'd have to look into as I've never done SSO before

**Comment by thau0x01** [comment]
Bro... its a command and control server!!!! 

who the fuck uses SSO in C2?

**Comment by its-a-feature** [comment]
This is supported in Mythic3.3 with Auth containers. You'd still need to write the logic (likely using a library) to handle the processing of SSO data and coming up with the right browser redirect (example in go is provided in the ExampleContainers repo in MythicMeta), but it's now possible
