### ISSUE TITLE
Scripting Tasking : command considered not loaded.

### ISSUE THREAD

**Issue by Capt-p** [its-a-feature/Mythic#275]
Hi ! I'm trying to run a command for every new callback checking in. As a starting point, I took the example from the Mythic Documentation (version 2.3) : https://docs.mythic-c2.net/scripting/scripting-examples#take-actions-on-new-callback . I also added the scripting base required given at https://docs.mythic-c2.net/scripting#scripting-base . I did not make any other changes and my server IP, server Port, username and password are correct.

I then run the script, execute a payload on a windows computer and get the following error : 

`AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'`

--> To solve that, I changed  `pending = asyncio.Task.all_tasks()` to `pending = asyncio.all_tasks()` 

If I run the script again and execute another payload I get :

`Exception in our try/catch while gathering responses: 404, message='Invalid response status', url=URL('wss://127.0.0.1:7443/ws/responses/by_task/%7B'error':%20'ls%20is%20not%20loaded%20in%20this%20callback',%20'cmd':%20'ls',%20'params':%20'.',%20'callback':%204%7D')`

I understand that my callback is considered to not have the ls command loaded, however, the ls command is loaded. I can run ls without problem from the web interface. I have the same result for any other command (even if I loaded all of the commands during the payload creation). 

I tried to use `mythic_rest.json_print(callback)` for troubleshooting, and my callback do have the correct process_name, user.... and a payload id.

What are my doing wrong here ? Also my version of Mythic from pip is 0.0.23 and my release of Mythic C2 is the latest from the master branch (v2.3.9). The Agent I use is Apollo and the profile is http.

Thanks in advance.

**Comment by Capt-p** [comment]
I forgot to add that the Agent I use is Apollo and the profile is http.

**Comment by its-a-feature** [comment]
Hey! Sorry things don't seem to be working out, let's see if we can figure out what's up. Can you:
1. attach the script you're running (sanitizing all sensitive info of course)
2. update the mythic pypi package to 0.0.38 (the latest release)
2. update Mythic to the latest from the master branch (should be v2.3.13 i believe) and test again.

**Comment by Capt-p** [comment]
[autoPersistGitHub.txt](https://github.com/its-a-feature/Mythic/files/11344469/autoPersistGitHub.txt)

Thank you very much for replying so fast. I attached the script I'm using as you asked. I'm also going to follow your recommendations (maybe the error is because I'm using Mythic C2 v2.3.9 https://github.com/its-a-feature/Mythic/releases/tag/v2.3.9 and not 2.3.13 ?).

**Comment by its-a-feature** [comment]
ah, looking back through that version of Mythic scripting, try doing 
```
results = await mythic.gather_task_responses(submit.response["id"], timeout=20)
```
the `response` field is a dictionary, it must be a typo in those old docs

**Comment by Capt-p** [comment]
Well I had already tried that either but then I get : 

```

  File "/home/kali/Desktop/AutoPersistGitHub.py", line 29
    results = await mythic.gather_task_responses(submit.response["id"], timeout=20)
TabError: inconsistent use of tabs and spaces in indentation
```

Even if there is no problem concerning indentation right  😅 ? I mean the indentation is the exact same as before. Sorry if I'm missing something but I don't see why.

**Comment by its-a-feature** [comment]
hmm are you able to switch the editor you're using to show spaces and tabs? if you copy-pasted that in then there might be tabs or spaces that weren't intended

**Comment by its-a-feature** [comment]
that first one has two tabs but the second one has 8 spaces (each of those little dots it shows is a space), that's why it's complaining about tabs vs spaces. Even though the end resulting indentation looks the same, to Python it's different (silly, i know)

**Comment by Capt-p** [comment]
Well I didn't know about that, thanks a lot. There is no python errors anymore, however I know get the following result : 

```
[+] got new callback, issuing ls
[*] waiting for ls results...
'id'
```
with no results coming even after 2 minutes. 

I also tried` results = await mythic.gather_task_responses(submit.response.id, timeout=20)` again just in case but still get `'dict' object has no attribute 'id'`.

**Comment by its-a-feature** [comment]
after this line:
```
submit = await mythic.create_task(task, return_on="completed")
```
can you do a `print(json.dumps(submit.to_json(), indent=2))`
I'm curious what's actually getting returned as a result of that call

**Comment by Capt-p** [comment]
The result is now : 

```
[+] got new callback, issuing ls
name 'json' is not defined
```

**Comment by its-a-feature** [comment]
oh, import `json` at the top of the file

**Comment by Capt-p** [comment]
yeah, i felt stupid at the moment I posted my message ...
```

[+] got new callback, issuing ls
{
  "response_code": 200,
  "raw_response": {
    "error": "ls is not loaded in this callback",
    "cmd": "ls",
    "params": ".",
    "callback": 49
  },
  "status": "error",
  "response": {
    "error": "ls is not loaded in this callback",
    "cmd": "ls",
    "params": ".",
    "callback": 49
  }
}

```

**Comment by its-a-feature** [comment]
that's why there's no "id" field to use for the next mythic call because ls was never issued.  So, for callback 49, does it have `ls` loaded? you can click the dropdown next for that callback in the active callbacks page and click metadata. You can scroll down there and see the list of commands available within the callback

**Comment by Capt-p** [comment]
All the commands included ls are loaded : 

![image](https://user-images.githubusercontent.com/95488808/234938147-7b0989f8-caf7-450b-8b81-d7b586ce097b.png)

Also ls is working correctly from the web interface : 

![image](https://user-images.githubusercontent.com/95488808/234938405-21904d0e-1df7-42a8-a343-83e75688f80a.png)

**Comment by Capt-p** [comment]
By the way, if I print the Callback object information with `await mythic_rest.json_print(callback)` we can see that there is no `supported_profiles` specified, could the have an incidence maybe ? 

```
{
  "init_callback": "04/27/2023 17:05:05",
  "last_checkin": "04/27/2023 17:05:05",
  "process_name": "apollo",
  "user": "user",
  "host": "WINDOWS",
  "pid": 5808,
  "ip": "10.0.2.4",
  "domain": "WINDOWS",
  "description": "Created by mythic_admin at 04/27/2023 12:14:29 UTC",
  "agent_callback_id": "521920d4-ee9a-47d8-babb-d13a994221bf",
  "external_ip": "",
  "payload_type_id": 1,
  "os": "Windows 10 Home 2009 6.2.9200.0",
  "architecture": "x64",
  "operator": {
    "username": "mythic_admin"
  },
  "active": true,
  "registered_payload": {
    "uuid": "f5b6b79d-0a69-4dd7-ad32-629fa70cc852"
  },
  "payload_type": {
    "ptype": "apollo"
  },
  "payload_description": "Created by mythic_admin at 04/27/2023 12:14:29 UTC",
  "integrity_level": 2,
  "operation": {
    "name": "Operation Chimera"
  },
  "tokens": [],
  "id": 49,
  "supported_profiles": []
}
```

**Comment by Capt-p** [comment]
Hello again @its-a-feature ! I've finally switched to the GraphQL interface instead of the REST, and I can now do what I wanted to do without any problem ! I'm actually still curious to understand why it wasn't working earlier with the REST, but just to let you know that if you don't have much time for it i have another way to work 👍

**Comment by its-a-feature** [comment]
oh nice!! I'm glad you switched to the GraphQL side! That makes things _SO_ much easier for me to help out since all of the REST endpoints are removed in the latest Mythic 3.0.0. 

I'm glad you got things working, and I'm glad the scripting examples from the new Jupyter notebook helped out. Those scripts are targeting Mythic 3.0.0, so a few things are a _little_ different (like the `display_id` vs `id` you saw there)

**Comment by Capt-p** [comment]
Yeah it's true things are way easier with GraphQL ! Honestly thank you very much to have taken of your time to help me out, it's really appreciated 👍 Mythic C2 is a very cool project and the customization features are super handy !
