### ISSUE TITLE
Mythic is broken after update

### ISSUE THREAD

**Issue by lsecqt** [its-a-feature/Mythic#284]
After updating mythic to v3.0.0 (https://github.com/its-a-feature/Mythic/releases/tag/v3.0.0) "mythic_postgres" docker container constantly restarts itself.

![image](https://github.com/its-a-feature/Mythic/assets/102690672/7d9e3509-1e2d-454f-93eb-677dff706a68)

Additionally, I am receiving the following error on Login:
```
Error getting JSON from server: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
![image](https://github.com/its-a-feature/Mythic/assets/102690672/85345c17-459f-4486-842d-cf5d599f9460)
Invalid login credentials do not output different error message.

My /opt/Mythic/postgres-docker/postgres.conf config is:
```
listen_addresses = '*'
logging_collector = off
```

**Comment by its-a-feature** [comment]
Is this a fresh install of Mythic 3.0 or did you try to update an existing Mythic install to this?

**Comment by lsecqt** [comment]
Confirmed!
Now Mythic is working after manual re-installation. Thank you for the amazing work!
