### ISSUE TITLE
Expanded Callbacks do not receive commands

### ISSUE THREAD

**Issue by lsecqt** [its-a-feature/Mythic#288]
When executing commands from Expanded Callback view, the commands are not issued at all. 

I navigate to separate callbacks by clicking the beacon arrow -> Expand Callback
![image](https://github.com/its-a-feature/Mythic/assets/102690672/21b4a15c-b975-4bd8-a143-1522ad6cb836)

While I can see previously issued command (from the main Active Callbacks view) I cannot issue new one.
![2023-05-17 18-39-58](https://github.com/its-a-feature/Mythic/assets/102690672/3c430051-89fd-4f6d-9000-e48beed4631d)

**Comment by its-a-feature** [comment]
I was able to reproduce this and will have it in the next update today. I'll message here when that update is pushed

**Comment by its-a-feature** [comment]
just made a push that'll fix this 👍
