### ISSUE TITLE
Not all Agents and Listeners Showing up

### ISSUE THREAD

**Issue by ZerkerEOD** [its-a-feature/Mythic#291]
I am testing the updated version 3.0 for my company, and when I install the agents and listeners, they don't all appear. 

![image](https://github.com/its-a-feature/Mythic/assets/26573385/b0e738f1-f387-41ff-a6ca-4bf168536441)

Here is what shows up though

![image](https://github.com/its-a-feature/Mythic/assets/26573385/69cafd17-61a6-4718-b43c-bc9457f1de9e)

So it looks like Athena needs to be included and come online on the cli. DNS profile needs to be included. Merlin is missing.

**Comment by its-a-feature** [comment]
`Merlin` isn't updated for v3.0 yet. I don't think `dns` is updated yet either (i wasn't aware anybody was using it since I don't think any public agents officially support it). I know the author of `athena` is doing updates, so i'm not sure why that one is restarting. Can you do `./mythic-cli logs athena`?

**Comment by ZerkerEOD** [comment]
Yeah looks to be repeating this:

```
Traceback (most recent call last):
  File "/Mythic/main.py", line 5, in <module>
    p = subprocess.Popen(["dotnet", "build", "--verbosity=q", "--nologo"], cwd="/Mythic/athena/agent_code/AthenaPlugins")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dotnet'
Traceback (most recent call last):
  File "/Mythic/main.py", line 5, in <module>
    p = subprocess.Popen(["dotnet", "build", "--verbosity=q", "--nologo"], cwd="/Mythic/athena/agent_code/AthenaPlugins")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dotnet'

```

I haven't used the DNS one, but because several testers are using it, I wanted additional listeners that could be used at some point if they deemed it. I hope the Merlin gets updated soon, though. It is one of my favorites.

**Comment by its-a-feature** [comment]
You can probably remove the `dns` one. Try re-installing `athena` - I think the author just made a push to fix it (`sudo ./mythic-cli install github https://github.com/MythicAgents/athena -f`). 

I know merlin is in the process of updating. All of the other agents simply just updated a few pieces for Mythic 3.0, but merlin is actually updating to remove all of the back-end Python code and replacing it with the new Golang version, so it's taking a bit longer.

**Comment by checkymander** [comment]
You had a small window to pull and get this bug 😂, sorry about that. I've already fixed it! Like he said just pull the most recent version and you should be good to go!

**Comment by ZerkerEOD** [comment]
@its-a-feature and @checkymander, thanks for the input. I always have that type of luck haha. I pulled the new version, and it installed immediately and looks to be running fine. I will keep an eye out for Merlin and will remove DNS. Thanks for the help.
