### ISSUE TITLE
Error getting json from server

### ISSUE THREAD

**Issue by Art-Fakt** [its-a-feature/Mythic#303]
Hi,
 I an error when I'm trying to connect to the Mythic Web-UI on port 7443.
it seems my authentification with my user to thepostgres db fails. But when I've seen I already have an user & pass in my .env file and my Postgres db container is running normally.

Here is my output from sudo ./mythic-cli logs mythic_server, 
{"level":"error","error":"pq: password authentication failed for user "mythic_user"","func":"github.com/its-a-feature/Mythic/database.getNewDbConnection","line":122,"host":"mythic_postgres","port":5432,"time":"2023-06-11T18:05:47Z","message":"Failed to connect to database"}

thanks if anyone can help me for that.

**Comment by its-a-feature** [comment]
Was this a clean install on a new system or did you upgrade something? It seems like the username for your postgres database and the .env file have gone out of sync. To fix, you'll either need to figure out the actual mythic_user password for postgres and update the .env file accordingly, or you'll need to run `./mythic-cli database reset` (this will completely drop all tables in the database and reset _everything_)

**Comment by Art-Fakt** [comment]
Thanks that's working when I tried the command when I try ./mythic-cli database restart, and retart mythic-cli and update the new mythic_admin password

thanks for your help
