### ISSUE TITLE
Error: Socks fails to open port

### ISSUE THREAD

**Issue by nspagnola-r7** [its-a-feature/Mythic#304]
Hello,

I was attempting to use the Socks proxy in the Apollo agent and received the follow error, `Failed to start listening on port 1080, it's not exposed through docker`. 

Tried working around this by adding in:
```
ports:
   - 1080:1080
```
And removing `network_mode: host` from the docker_compose.yml file which ended up causing an additional error causing the agent to report as being offline.

**Comment by its-a-feature** [comment]
Hi! Great question!

Go ahead and set that docker-compose configuration back to how it was for `apollo`. That error isn't coming from the `apollo` container, but rather from Mythic. When you try to start `socks`, Mythic wants to open up a port on the `mythic_server` container so it can route traffic. If you look in your `.env` file for Mythic you'll see the following two entries:
```
MYTHIC_SERVER_DYNAMIC_PORTS="7000-7010"
MYTHIC_SERVER_DYNAMIC_PORTS_BIND_LOCALHOST_ONLY="false"
```
If you want to use a port that's _not_ in that range, then simply add it:
```
MYTHIC_SERVER_DYNAMIC_PORTS="7000-7010,1080"
MYTHIC_SERVER_DYNAMIC_PORTS_BIND_LOCALHOST_ONLY="false"
```
and start the Mythic server again `./mythic-cli start mythic_server` and you should be good to go.
You can of course change it with `./mythic-cli config set mythic_server_dynamic_ports 7000-7010,1080`

**Comment by nspagnola-r7** [comment]
Ahh okay good to know. Thanks for the assistance and quick response!

**Comment by its-a-feature** [comment]
I'll update that error message in the UI with more context (like i added here)

**Comment by MexHigh** [comment]
@its-a-feature Just ran into the same issue since I didn't know that the dynamic ports are bound to 127.0.0.1 by default. I think documenting this feature on the SOCKS page is important!
