### ISSUE TITLE
Download stalled implant (implant still checking in but not interactive)

### ISSUE THREAD

**Issue by rolen** [its-a-feature/Mythic#308]
Currently on an engagement, tried to download a file and the beacon is stalled. It is checking in but it is not interactive. Looking at the webserver logs on the redirector (nginx) I can see that the implant is POSTing back (looks same kinda size every time so assume its sending the same message that the server side of the implant is not processing properly). I've tried to enable the debug interface on rabbitmq (stop docker and edit hostconfig.json etc to pass the ports through to localhost) to see what is going onto the queue but every time I set management port (15672) rabbit refuses to start back up. Is there anything else I can debug or that you can recommend? 

Using Apfell with dynamichttp (not gonna say how or where :-)) 
Version 2.3.13
Target machine is Ventura

**Comment by its-a-feature** [comment]
how big is the file you're trying to download? Apfell is a single-threaded agent (due to a limitation in the JXA language I haven't been able to get around), so if it's a big download, then apfell will continue to send a chunk each time it checks in, but won't be able to process additional messages. To check, you can go to your file downloads page and you should see that the file you're downloading is at X/Y chunks

**Comment by rolen** [comment]
Not that big tbh, its a .zsh_history file, the file is about 13kb in size and the message being posted is 24kb (that is size of the payload after stripping away the wrapper and base64 decoding it, ie the byte count). Just had a look in the Files page and it isn't listed there I'm afraid

**Comment by its-a-feature** [comment]
You're on an older version of Mythic (2.3.13) - did you install the matching version of apfell (https://github.com/MythicAgents/apfell/releases/tag/v2.3.13)?

**Comment by rolen** [comment]
Not specifically no, hadn't even crossed my mind tbh. So `install` command doesn't take that into account?

**Comment by rolen** [comment]
Has the code around downloading specifically changed?

Looking at the line number where the exception is being thrown its this 

`try:
        file_meta = await app.db_objects.get(db_model.filemeta_query, agent_file_id=data["file_id"])
`

looking at the corresponding download code within the implant, looks like it is sending the `file_id` so not sure what is going 

`
let data = handle.readDataOfLength(chunkSize);
while (parseInt(data.length) > 0 && offset < fileSize) {
       // send a chunk
       let fileData = { 'chunk_num': currentChunk, 'chunk_data': data.base64EncodedStringWithOptions(0).js, 'file_id': registerFile['responses'][0]['file_id'] };
       let response = this.postResponse(task, fileData);
`

Think the reason that the beacon has stalled is that within the code for download within the implant is that it loops if it doesn't get success back
`
while (parseInt(data.length) > 0 && offset < fileSize) {
                    // send a chunk
    ... 
                    if (response['responses'][0]['status'] === 'success') {
                        offset += parseInt(data.length);
                        handle.seekToFileOffset(offset);
                        currentChunk += 1;
                        data = handle.readDataOfLength(chunkSize);
                    }
                    $.NSThread.sleepForTimeInterval(this.gen_sleep_time());
                }
`
Think what I'll do is change the exception handler on line 758 within `file_api.py` so that it just returns `"status": "success"` and hopefully the implant breaks out of this loop and then work out another way to get files back down, fingers crossed. 

Thanks for your help!!

**Comment by its-a-feature** [comment]
did you ever get a message displayed for your task like this:
https://github.com/MythicAgents/apfell/blob/v2.3.13/Payload_Type/apfell/agent_code/c2_profiles/dynamichttp.js#L480-L483

**Comment by its-a-feature** [comment]
I'm going to close this as being stale, but if you're still having the issue with the latest apfell and mythic, please let me know
