### ISSUE TITLE
 SQL Syntax Error in RPC Query

### ISSUE THREAD

**Issue by buzz075** [its-a-feature/Mythic#312]
File: mythic-docker/src/rabbitmq/recv_mythic_rpc_agentstorage_search.go
Line: 45:
```go
if err := database.DB.Select(&agentStorageMessages, `SELECT
        *
        FROM agentstorage
        WHERE unique_id ILIKE %$1%`, input.SearchUniqueID);

The `ILIKE %$1%` is invalid syntax for the pq library. Calling this function returns an error: `pq: syntax error at or near "%"\`
Someone else had the same issue on SO with a very similar query:  https://stackoverflow.com/questions/25214459/go-postgresql-like-query 

Changinge to 
`ILIKE '%' || $1 || '%'` 
seems to resolve the error, as mentioned in the SO post

**Comment by its-a-feature** [comment]
Good catch! I actually noticed that a few of the other RPC commands had errors as well. I just did a push that fixed the agent storage search, artifact search, and process search functionality.

**Comment by its-a-feature** [comment]
If that fix last week didn't fix the issue for you, can you reopen this and we can continue discussing what the issue might be?
