### ISSUE TITLE
16 byte UUIDs/small messages not working properly

### ISSUE THREAD

**Issue by DarkC0ntributor** [its-a-feature/Mythic#314]
With v3 there is a length check on incoming messages. If a message is less then 37 bytes its rejected (https://github.com/its-a-feature/Mythic/blob/7e68ace90f8904628ece90f2a00dcfb746349675/mythic-docker/src/rabbitmq/util_agent_message.go#L264).

I am using 16 byte UUIDs and a small get_tasking message (turned into the real one by a translation container)
so my agent is ending up with 404s (when using HTTP).
Padding the payload with zeros works, but it defeats the purpose of smaller messages :smiley:

**Comment by its-a-feature** [comment]
Good catch! I didn't realize somebody would be sending messages so small! I just made a push that should support your smaller messages if you could pull that and give it a try

**Comment by its-a-feature** [comment]
if it turns out this doesn't fix the issue, please reopen this and we can see what's still wrong
