### ISSUE TITLE
build.env not working for Mythic_CLI

### ISSUE THREAD

**Issue by mr-m0nst3r** [its-a-feature/Mythic#316]
I'm using build.env for goproxy, but seems Mythic_CLI is not working.

<img width="447" alt="image" src="https://github.com/its-a-feature/Mythic/assets/38524240/4fd2bae2-2950-4fb3-824d-44e51fde4d6e">

here's the build.env:
```
ubuntu@mythic:~/Mythic$ cat build.env
PIP_INDEX="ali"
PIP_INDEX_URL="https://mirrors.aliyun.com/pypi/simple/"
PIP_TRUSTED_HOST="mirrors.aliyun.com"
GOPROXY="https://goproxy.io,direct"
GO111MODULE="on"
```

here's the changed Mythic_CLI/Dockerfile:
```
FROM itsafeaturemythic/mythic_go_base:latest

WORKDIR /usr/src/app

ARG GOPROXY
ARG GO111MODULE

RUN go env -w GOPROXY=${GOPROXY}
RUN go env -w GO111MODULE=${GO111MODULE}

COPY ["src/", "."]


CMD ["/bin/bash", "-c", "make", "build"]
```

Strange thing is: same syntax is working for `mythic-docker`, but not for this, I have to hardcode the raw Dockerfile for the goproxy.

Any ideas?

**Comment by its-a-feature** [comment]
Ah yeah, the mythic services use docker-compose to build, but `mythic-cli` is just using a raw docker command to run, so it's not leveraging those same settings. Good catch!

**Comment by mr-m0nst3r** [comment]
it's the same problem with http c2 profile. I also changed the Dockerfile to use build.env, but same problem happened.

Looking forward to a working fix, so I don't have to fork and hardcode proxies.

**Comment by its-a-feature** [comment]
I just did a push that should allow you to leverage the `GOPROXY` and `GO111MODULE` values for mythic_server and mythic-cli. Make sure to add them to your `build.env` for the build process and `.env` for when containers are running (like a nested build with mythic_docker). Assuming all that works as expected, I can follow a similar process for other services like the `http` profile

**Comment by mr-m0nst3r** [comment]
Hi mate, I've deleted all the previouse instance and built it from starting, it's smooth like silk. Keep up the great C2!
