### ISSUE TITLE
Bad redirect of the mythic_server GOPROXY

### ISSUE THREAD

**Issue by w1ld3r** [its-a-feature/Mythic#319]
Having place the mythic stack behind an https reverse proxy, the mythic-proxy is listeneing on 9243 (0.0.0.0:9243->9243/tcp) after setting the NGINX_PORT to 9243 in  an `.env` file.
When accessing the mythic_server using my https reverse proxy (ex: https://mythic.domain.net/) it redirects me to https://mythic.domain.net:9243/new/login.
Is there a way to configure properly the mythic server proxy to redirect to the good location ?

**Comment by its-a-feature** [comment]
How is your reverse proxy set up? I just tested this and it appears to be just an issue with these two redirects https://github.com/its-a-feature/Mythic/blob/master/nginx-docker/config/templates/services.conf.template#L9-L10. If you explicitly go to `https://mythic.domain.net/new/login` then it appears that everything else proxies and works correctly. 

I'll look into why those two redirects are different than the others and how to keep the port from changing

**Comment by w1ld3r** [comment]
Yes exactly, the backend is working at /new/login. The bad redirect is just inconvenient.

**Comment by its-a-feature** [comment]
This will be available in the next release. FWIW if you want to make the change now, it's as simple as adding `absolute_redirect off;` after this line https://github.com/its-a-feature/Mythic/blob/master/nginx-docker/config/templates/services.conf.template#L7

**Comment by w1ld3r** [comment]
Thanks for your reactivity !
