### ISSUE TITLE
server side error while browsing to some tabs

### ISSUE THREAD

**Issue by qxmx** [its-a-feature/Mythic#32]
Hello, I'm installing apfell 1.4 on ubuntu 16.04 (a clean one). Installation is smooth and server is up (I set server_ip to 127.0.0.1), however when I browse to http://127.0.0.1/payloads, there's an popup window saying "websocket closed... ". 
Similar error happen on 127.0.0.1/c2profile_management, saying "failed to get the current operation". Inspecting by google chrome and have this in console: 
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at get_parameter_instance_callback (c2profile_management:1766)
    at XMLHttpRequest.xhr.onreadystatechange (c2profile_management:1202)

What shall I do now ? Could you please help me?

**Comment by its-a-feature** [comment]
Do you have an active operation? Go to the Operations Management page and make sure there's at least one entry and that you have it marked as your "current operation"

**Comment by rgzn-aiyun** [comment]
> Do you have an active operation? Go to the Operations Management page and make sure there's at least one entry and that you have it marked as your "current operation"

Global C2 Profile Configurations

Websocket closed.
Please refresh to re-establish connections or select an active operation

**Comment by its-a-feature** [comment]
Manage Operations -> Operations Management. You should see a table at the top with the list of operations that are available. Assuming you have big red letters in the top navigation bar saying that you need to select an active operation, you need to select the default operation from this table and mark it as your "current operation". You'll see the big letters at the top change to be the name of the operation. Those errors should then go away.

The errors are popping up because you're trying to view operation specific information, but have no operation selected.

**Comment by qxmx** [comment]
Thank you, this works for me. I make the default operation as current operation and all errors gone.

**Comment by rgzn-aiyun** [comment]
> Manage Operations -> Operations Management. You should see a table at the top with the list of operations that are available. Assuming you have big red letters in the top navigation bar saying that you need to select an active operation, you need to select the default operation from this table and mark it as your "current operation". You'll see the big letters at the top change to be the name of the operation. Those errors should then go away.
> 
> The errors are popping up because you're trying to view operation specific information, but have no operation selected.

 default,Completed：Complete Operation

**Comment by rgzn-aiyun** [comment]
The error did not disappear?

**Comment by its-a-feature** [comment]
@rgzn-aiyun can you share a screenshot of that page?

**Comment by rgzn-aiyun** [comment]
> @rgzn-aiyun can you share a screenshot of that page?

![JF30LFK8XEQOS148WG }U(D](https://user-images.githubusercontent.com/45959815/89601446-2293e300-d897-11ea-9f15-e1848c6a829e.png)

**Comment by its-a-feature** [comment]
and you still get those websocket errors on some pages? 🤔  it's not marked as complete is it?

**Comment by rgzn-aiyun** [comment]
> and you still get those websocket errors on some pages? 🤔 it's not marked as complete is it?

![QL%TH(INNL5S(GIGFQJ5 {O](https://user-images.githubusercontent.com/45959815/89601595-874f3d80-d897-11ea-8041-ba74ea979d46.png)

**Comment by rgzn-aiyun** [comment]
Very strange

**Comment by its-a-feature** [comment]
can you run `sudo ./status_check.sh` and paste the results here? I'm curious if something is up with the docker containers. The fact that you can see operations listed on that operations management page means that websockets are working in general. And if you have that `default` operation marked as your current one and not completed, and you're still getting errors, that makes me think there's something up with the containers.

**Comment by rgzn-aiyun** [comment]
> can you run `sudo ./status_check.sh` and paste the results here? I'm curious if something is up with the docker containers. The fact that you can see operations listed on that operations management page means that websockets are working in general. And if you have that `default` operation marked as your current one and not completed, and you're still getting errors, that makes me think there's something up with the containers.

![RYFFXFZX@ SZ9M2I}~67YGD](https://user-images.githubusercontent.com/45959815/89602465-5d971600-d899-11ea-8e9b-63903c65fa46.png)

**Comment by its-a-feature** [comment]
Ah yup, right there - something is wrong with the rabbitmq container. It keeps restarting. That would explain why now that you have an operation set, the containers aren't checking in (the containers all communicate via the rabbitmq container). can you do `sudo ./display_output.sh apfell_rabbitmq` and see if there are any errors at the end that might indicate what's up?

**Comment by rgzn-aiyun** [comment]
> Ah yup, right there - something is wrong with the rabbitmq container. It keeps restarting. That would explain why now that you have an operation set, the containers aren't checking in (the containers all communicate via the rabbitmq container). can you do `sudo ./display_output.sh apfell_rabbitmq` and see if there are any errors at the end that might indicate what's up?

![_H{8T$MMQL$M8E9YD}A(X2D](https://user-images.githubusercontent.com/45959815/89602799-1eb59000-d89a-11ea-899a-392506d14ab6.png)

**Comment by its-a-feature** [comment]
hm... kernel pid terminated? 🤔  sounds like your host vm killed it for some reason. try `sudo ./start_apfell.sh` again (it'll bring everything down then back up), then you can use that `sudo ./status.check.sh` command again to see if it's going back to that restarting state again. I wonder if your host got pegged for resources somewhere and killed it?

**Comment by rgzn-aiyun** [comment]
> hm... kernel pid terminated? 🤔 sounds like your host vm killed it for some reason. try `sudo ./start_apfell.sh` again (it'll bring everything down then back up), then you can use that `sudo ./status.check.sh` command again to see if it's going back to that restarting state again. I wonder if your host got pegged for resources somewhere and killed it?

Still the same error, the memory is 32G, it is impossible that there is not enough memory!

**Comment by its-a-feature** [comment]
oh geez lol yeah that's definitely not the issue then. can you paste more of that output from the rabbitmq error? maybe there's something else in there indicating what's up

**Comment by rgzn-aiyun** [comment]
> oh geez lol yeah that's definitely not the issue then. can you paste more of that output from the rabbitmq error? maybe there's something else in there indicating what's up


[log.zip](https://github.com/its-a-feature/Apfell/files/5039107/log.zip)

**Comment by rgzn-aiyun** [comment]
@its-a-feature 

what is the problem?

**Comment by its-a-feature** [comment]
I'm trying to google what the error might be because it's not something I've encountered before. Looks to be some sort of odd initialization race condition with docker? try this: `sudo ./reset_rabbitmq_data.sh` and `sudo ./reset_postgres_database.sh` then `sudo ./start_apfell.sh`. I'm hoping that by just clearing all the associated data and starting again, it'll be fixed?

**Comment by rgzn-aiyun** [comment]
> I'm trying to google what the error might be because it's not something I've encountered before. Looks to be some sort of odd initialization race condition with docker? try this: `sudo ./reset_rabbitmq_data.sh` and `sudo ./reset_postgres_database.sh` then `sudo ./start_apfell.sh`. I'm hoping that by just clearing all the associated data and starting again, it'll be fixed?

The problem has been solved, but it seems that you cannot add commands
×
Error: failed to get command

**Comment by its-a-feature** [comment]
🤔  Where were you adding commands? The entire back-end structure for all that is changing with the update next week

**Comment by rgzn-aiyun** [comment]
> 🤔 Where were you adding commands? The entire back-end structure for all that is changing with the update next week

Select a C2 Profile to add to your payload.

**Comment by its-a-feature** [comment]
Now that the latest version is out, please use that one. I'm gonna close this and if you're still having issues with the latest version, we can re-address there. The code-base is just so different between the two
