### ISSUE TITLE
Error: 'createTask' has no argument named 'callback_ids'

### ISSUE THREAD

**Issue by mattbrun** [its-a-feature/Mythic#328]
Hi all,
after a break on a project (about 1 month), I went back to the Mythic web console, and strangely enough since a couple of days I started having errors working with callbacks.
Looking at the web browser console I see errors which seems related to the websocket/grapqhl calls.
After the break I actually checked for updates on some payloads server side, but from what I remember the callbacks console was still working after the update.

In the following screenshots you can see the output of trying to run the `help` command on the callback.
**Firefox**
![Screenshot from 2023-09-15 11-24-17](https://github.com/its-a-feature/Mythic/assets/1902043/0f1b60dc-7a09-49a0-accb-495319ff2852)

**Chromium**
![Screenshot from 2023-09-15 11-24-24](https://github.com/its-a-feature/Mythic/assets/1902043/416d2779-7d3c-4164-b5b5-3b03ad43904b)

Another strange thing is that the browser is telling me the HTTPS certificate is self-signed, but it's actually generated with `certbot` and signed by Let's Encrypt. I double-checked server side (and even renewed) the certificate, and it should be ok. I'm using `nginx` as a reverse proxy.
I'm not sure if this may interfere with the web-sockets connection.

Any thoughts on the situation?

Thanks for your support!
Best regards,
M

**Comment by its-a-feature** [comment]
When you updated, what all did you do? That error appears as though one of the Hasura config files wasn't pulled in

**Comment by mattbrun** [comment]
I updated a couple of payloads (i.e. Apollo and I don't remember which is the second one) through `sudo ./mythic-cli install github https://github.com/MythicAgents/apollo` from the repo dir I cloned.

**Comment by daestar** [comment]
I wanted to put this out there. I was running into the same issue after doing a `git pull` from version 3.0.0 to 3.0.1-rc46. I was using the freyja agent. However, a clean install did not present the error.

**Comment by its-a-feature** [comment]
Out of curiosity, after you did a `git pull` what did you run? and do you have `REBUILD_ON_START="false"` or true?

**Comment by daestar** [comment]
I ran `sudo make` followed by `sudo ./mythic-cli start` and `REBUILD_ON_START` was set to true.

**Comment by its-a-feature** [comment]
As there's another newer release of Mythic out now, `v3.1.2`, I'd recommend updating to that one and re-opening this if you're still having the issue
