### ISSUE TITLE
Unable to connect to Mythic Web UI port(7443)

### ISSUE THREAD

**Issue by sunny99sun** [its-a-feature/Mythic#330]
I can't access the port the Nginx port(7443) .

Output about status,  and  logs：

# ./mythic-cli status
MYTHIC SERVICE          WEB ADDRESS             BOUND LOCALLY
Nginx (Mythic Web UI)   https://127.0.0.1:7443   false
Mythic Backend Server   http://127.0.0.1:17443   true
Hasura GraphQL Console  http://127.0.0.1:8080    true
Jupyter Console         http://127.0.0.1:8888    true
Internal Documentation  http://127.0.0.1:8090    true

ADDITIONAL SERVICES     IP                      PORT    BOUND LOCALLY
Postgres Database       127.0.0.1               5432     true
React Server            127.0.0.1               3000     true
RabbitMQ                127.0.0.1               5672     true

Mythic Main Services
CONTAINER NAME          STATE           STATUS                          PORTS
mythic_documentation    running         Up About a minute (healthy)     8090/tcp -> 127.0.0.1:8090
mythic_graphql          running         Up About a minute (healthy)     8080/tcp -> 127.0.0.1:8080
mythic_jupyter          running         Up About a minute (healthy)     8888/tcp -> 127.0.0.1:8888
mythic_nginx            running         Up About a minute (healthy)     7443/tcp -> :::7443, 7443
mythic_postgres         running         Up About a minute (healthy)     5432/tcp -> 127.0.0.1:5432
mythic_rabbitmq         running         Up About a minute (healthy)     5672/tcp -> 127.0.0.1:5672
mythic_react            running         Up About a minute (healthy)     3000/tcp -> 127.0.0.1:3000
mythic_server           running         Up About a minute (healthy)     7000/tcp -> :::7000, 7001/tcp -> :::7001, 7002/tcp -> :::7002, 7003/tcp -> :::7003, 7004/tcp -> :::7004, 7005/tcp -> :::7005, 7006/tcp -> :::7006, 7007/tcp -> :::7007, 7008/tcp -> :::7008, 7009/tcp -> :::7009, 7010/tcp -> :::7010, 17443/tcp -> 127.0.0.1:17443, 17444/tcp -> 127.0.0.1:17444, 7000, 7001, 7002, 7003, 7004, 7005, 7006, 7007, 7008, 7009, 7010

Installed Services
CONTAINER NAME  STATE           STATUS                  PORTS
apfell          running         Up About a minute
basic_logger    running         Up About a minute
http            running         Up About a minute
merlin          running         Up About a minute

[*] RabbitMQ is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
    Use 'sudo ./mythic-cli config set rabbitmq_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this

[*] MythicServer is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
    Use 'sudo ./mythic-cli config set mythic_server_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
[*] If you are using a remote PayloadType or C2Profile, they will need certain environment variables to properly connect to Mythic.
    Use 'sudo ./mythic-cli config service' for configs for these services.

# ./mythic-cli logs mythic_nginx
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/services.conf.template to /etc/nginx/conf.d/services.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
172.19.0.1 - - [07/Oct/2023:10:08:59 +0000] "GET / HTTP/1.1" 301 169 "-" "Go-http-client/1.1" "-"
172.19.0.1 - - [07/Oct/2023:10:08:59 +0000] "GET /new/login HTTP/1.1" 200 585 "https://127.0.0.1:7443" "Go-http-client/1.1" "-"
127.0.0.1 - - [07/Oct/2023:10:09:09 +0000] "GET /new/login HTTP/1.1" 200 585 "-" "curl/7.88.1" "-"
127.0.0.1 - - [07/Oct/2023:10:09:39 +0000] "GET /new/login HTTP/1.1" 200 585 "-" "curl/7.88.1" "-"
127.0.0.1 - - [07/Oct/2023:10:10:09 +0000] "GET /new/login HTTP/1.1" 200 585 "-" "curl/7.88.1" "-"
127.0.0.1 - - [07/Oct/2023:10:10:39 +0000] "GET /new/login HTTP/1.1" 200 585 "-" "curl/7.88.1" "-"

# ./mythic-cli logs mythic_server
Step 1/6 - Initializing utilities
Step 2/6 - Initializing logging
Step 3/6 - Initializing database
{"level":"error","error":"dial tcp 172.19.0.4:5432: connect: connection refused","func":"github.com/its-a-feature/Mythic/database.getNewDbConnection","line":163,"host":"mythic_postgres","port":5432,"time":"2023-10-07T10:08:39Z","message":"Failed to connect to database"}
Step 3.5/6 - Initializing MITRE ATT&CK
Step 4/6 - Initializing webserver
Step 5/6 - Initializing rabbitmq
{"level":"error","error":"dial tcp 172.19.0.8:5672: connect: connection refused","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).GetConnection","line":127,"time":"2023-10-07T10:08:47Z","message":"Failed to connect to rabbitmq"}
Step 6/6 - Starting webserver
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"http","c2profiles":["http","dynamichttp"],"time":"2023-10-07T10:08:54Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"dynamichttp","c2profiles":["http","dynamichttp"],"time":"2023-10-07T10:08:54Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"dynamichttp","c2profiles":["http","dynamichttp"],"time":"2023-10-07T10:08:57Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeWrappers","line":525,"wrapper":"service_wrapper","wrapped":"merlin","time":"2023-10-07T10:08:57Z","message":"Failed to find payloadtype to associate for wrapping"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeWrappers","line":525,"wrapper":"scarecrow_wrapper","wrapped":"merlin","time":"2023-10-07T10:08:57Z","message":"Failed to find payloadtype to associate for wrapping"}

**Comment by its-a-feature** [comment]
The output you're showing for the `mythic_nginx` container shows that its getting back 200 response codes. What happens when you try to visit it in the browser? Can you also provide:

- OS where Mythic is running
- Browser you're trying to access from
- Where you're trying to access from

**Comment by sunny99sun** [comment]
Sorry, please close. I found that the browser has a proxy enabled, so it cannot be accessed.
