### ISSUE TITLE
When agent connect to server,server send  400 Bad Request to agent. Active Callbacks have no connection. somewhere have trouble in server.how to resolve it？

### ISSUE THREAD

**Issue by liqingjia** [its-a-feature/Mythic#339]
![企业微信截图_16987450196917](https://github.com/its-a-feature/Mythic/assets/12861709/906f1b72-9068-4514-8c15-91afcf7acffa)

**Comment by its-a-feature** [comment]
The server will typically send back a 400 error if there's something that it fails to process with the agent's message. Run `sudo ./mythic-cli logs mythic_server` to see if there are any errors getting printed that match up to the 400 response codes you're getting.

**Comment by liqingjia** [comment]
when I use sudo ./mythic-cli logs mythic_server,
#No RabbitMQ Route for apollo_pt_rpc_resync
#No RabbitMQ Route for athena_pt_rpc_resync
#No RabbitMQ Route for poseidon_pt_rpc_resync

the mythic_rabbitmq CONTAINER is running
![企业微信截图_20231106100053](https://github.com/its-a-feature/Mythic/assets/12861709/f9bfbe0e-1324-4bfa-b9c7-fcbf8e4fab9f)

how can I do to solve it?

the logs like this:
{"level":"error","error":"#No RabbitMQ Route for athena_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":306,"errorCode":312,"errorText":"NO_ROUTE","time":"2023-11-06T01:21:05Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"#No RabbitMQ Route for athena_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendPTRPCReSync","line":32,"time":"2023-11-06T01:21:05Z","message":"Failed to send RPC message"}
{"level":"error","error":"#No RabbitMQ Route for athena_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.reSyncPayloadTypes","line":1127,"time":"2023-11-06T01:21:05Z","message":"Failed to ask payload type to resync"}
{"level":"error","error":"#No RabbitMQ Route for poseidon_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":306,"errorCode":312,"errorText":"NO_ROUTE","time":"2023-11-06T01:21:05Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"#No RabbitMQ Route for poseidon_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendPTRPCReSync","line":32,"time":"2023-11-06T01:21:05Z","message":"Failed to send RPC message"}
{"level":"error","error":"#No RabbitMQ Route for poseidon_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.reSyncPayloadTypes","line":1127,"time":"2023-11-06T01:21:05Z","message":"Failed to ask payload type to resync"}
{"level":"error","error":"#No RabbitMQ Route for freyja_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":306,"errorCode":312,"errorText":"NO_ROUTE","time":"2023-11-06T01:21:05Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"#No RabbitMQ Route for freyja_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendPTRPCReSync","line":32,"time":"2023-11-06T01:21:05Z","message":"Failed to send RPC message"}
{"level":"error","error":"#No RabbitMQ Route for freyja_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.reSyncPayloadTypes","line":1127,"time":"2023-11-06T01:21:05Z","message":"Failed to ask payload type to resync"}
{"level":"error","error":"#No RabbitMQ Route for apollo_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":306,"errorCode":312,"errorText":"NO_ROUTE","time":"2023-11-06T01:21:06Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"#No RabbitMQ Route for apollo_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendPTRPCReSync","line":32,"time":"2023-11-06T01:21:06Z","message":"Failed to send RPC message"}
{"level":"error","error":"#No RabbitMQ Route for apollo_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.reSyncPayloadTypes","line":1127,"time":"2023-11-06T01:21:06Z","message":"Failed to ask payload type to resync"}
{"level":"error","error":"#No RabbitMQ Route for athena_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":306,"errorCode":312,"errorText":"NO_ROUTE","time":"2023-11-06T01:21:06Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"#No RabbitMQ Route for athena_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendPTRPCReSync","line":32,"time":"2023-11-06T01:21:06Z","message":"Failed to send RPC message"}
{"level":"error","error":"#No RabbitMQ Route for athena_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.reSyncPayloadTypes","line":1127,"time":"2023-11-06T01:21:06Z","message":"Failed to ask payload type to resync"}
{"level":"error","error":"#No RabbitMQ Route for poseidon_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":306,"errorCode":312,"errorText":"NO_ROUTE","time":"2023-11-06T01:21:06Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"#No RabbitMQ Route for poseidon_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendPTRPCReSync","line":32,"time":"2023-11-06T01:21:06Z","message":"Failed to send RPC message"}
{"level":"error","error":"#No RabbitMQ Route for poseidon_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.reSyncPayloadTypes","line":1127,"time":"2023-11-06T01:21:06Z","message":"Failed to ask payload type to resync"}
{"level":"error","error":"#No RabbitMQ Route for freyja_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":306,"errorCode":312,"errorText":"NO_ROUTE","time":"2023-11-06T01:21:06Z","message":"failed to deliver message to exchange/queue, NotifyReturn"}
{"level":"error","error":"#No RabbitMQ Route for freyja_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendPTRPCReSync","line":32,"time":"2023-11-06T01:21:06Z","message":"Failed to send RPC message"}
{"level":"error","error":"#No RabbitMQ Route for freyja_pt_rpc_resync. Is the container online (./mythic-cli status)?\n#If the container is online, there might be an issue within the container processing the request (./mythic-cli logs [container name]). ","func":"github.com/its-a-feature/Mythic/rabbitmq.reSyncPayloadTypes","line":1127,"time":"2023-11-06T01:21:06Z","message":"Failed to ask payload type to resync"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"tcp","c2profiles":["tcp","smb"],"time":"2023-11-06T01:21:06Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"smb","c2profiles":["tcp","smb"],"time":"2023-11-06T01:21:06Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeWrappers","line":525,"wrapper":"scarecrow_wrapper","wrapped":"apollo","time":"2023-11-06T01:21:06Z","message":"Failed to find payloadtype to associate for wrapping"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeWrappers","line":525,"wrapper":"service_wrapper","wrapped":"apollo","time":"2023-11-06T01:21:06Z","message":"Failed to find payloadtype to associate for wrapping"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"websocket","c2profiles":["websocket"],"time":"2023-11-06T01:21:06Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"discord","c2profiles":["discord","websocket","slack","smb"],"time":"2023-11-06T01:21:07Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"websocket","c2profiles":["discord","websocket","slack","smb"],"time":"2023-11-06T01:21:07Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"slack","c2profiles":["discord","websocket","slack","smb"],"time":"2023-11-06T01:21:07Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"sql: no rows in result set","func":"github.com/its-a-feature/Mythic/rabbitmq.updatePayloadTypeC2Profiles","line":469,"c2profile":"smb","c2profiles":["discord","websocket","slack","smb"],"time":"2023-11-06T01:21:07Z","message":"Failed to get c2profile to associate with payloadtype"}
{"level":"error","error":"message delivery confirmation timed out in SendRPCMessage","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendRPCMessage","line":310,"time":"2023-11-06T01:30:54Z","message":"message delivery confirmation to exchange/queue timed out"}
{"level":"error","error":"message delivery confirmation timed out in SendRPCMessage","func":"github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).SendC2RPCOpsecCheck","line":36,"time":"2023-11-06T01:30:54Z","message":"Failed to send RPC message"}

**Comment by its-a-feature** [comment]
I think those errors are generally fine as it's typically a timing issue with syncing. What agent and c2 profile are you using? I've seen issues where two C2 profiles are trying to use the same port (which won't work), so that's something to check too and make sure that there's not another C2 profile bound to the port you're trying to use. When Mythic throws an error, it sends back 404 to the agent, not 400. 400 sounds like there's a protocol level mismatch happening

**Comment by its-a-feature** [comment]
If you're still having this issue, please open it back up and we can try to address it again
