### ISSUE TITLE
Misleading status after payload creation.

### ISSUE THREAD

**Issue by timukas** [its-a-feature/Mythic#340]
He,

Using latest version of Mythic (agents and payloads) on Linux.

I've noticed, that it shows 'wrong' status after payload creation. It's always set to 'Error', but payloads works without any issues.
Tried with different Linux ELF payloads - Athena, Poseidon, zippy etc.

Build progress icons are green:

![image](https://github.com/its-a-feature/Mythic/assets/1915618/68311ac4-595f-41c8-bab5-5eb082b41041)

But inside each 'bubble' status shows 'Error':

![image](https://github.com/its-a-feature/Mythic/assets/1915618/226c3078-f595-41f8-ae62-f14e5d49a8bc)
![image](https://github.com/its-a-feature/Mythic/assets/1915618/913f0094-f47e-4c1b-a2c2-0ed43124ad96)
![image](https://github.com/its-a-feature/Mythic/assets/1915618/7e9ede02-3664-44ce-8da7-745f4cb84a39)

**Comment by its-a-feature** [comment]
Great catch! I just pushed an update to fix this. The new UI version should show as 0.1.26; can you update and confirm it's working for you?

**Comment by timukas** [comment]
Now status is correct on latest UI version.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/885794a3-4abd-45f2-9aae-aa333bf32f20)


![image](https://github.com/its-a-feature/Mythic/assets/1915618/94e9ef30-8f7b-4259-aacd-00618462a471)
