### ISSUE TITLE
[UI bug] Switching operation didn't switch list of active callbacks

### ISSUE THREAD

**Issue by XCVYN6UGT85JywuH** [its-a-feature/Mythic#342]
When you switch operation, list of active callbacks remains for the previous operation, until you reload your page.

**Comment by its-a-feature** [comment]
You're exactly right! Thanks for mentioning that. I have a fix ready for it and hopefully it'll be pushed out tomorrow

**Comment by its-a-feature** [comment]
this should be fixed with the latest Mythic push, 3.2.0 and UI version 0.1.29

**Comment by XCVYN6UGT85JywuH** [comment]
Thx
