### ISSUE TITLE
Sorting of IP address in C2 UI.

### ISSUE THREAD

**Issue by timukas** [its-a-feature/Mythic#344]
Hi,

On 'Active Callbacks' page IP addresses can be sorted numerically by octets.

Currently sorting by IPs looks a bit misleading:

![image](https://github.com/its-a-feature/Mythic/assets/1915618/7f3096db-8fbf-4bfc-bac3-11ff6322f7b5)

**Comment by its-a-feature** [comment]
Good catch! They were definitely just getting sorted as strings, but that should be fixed now with the latest push. Can you pull that and give it a try?

**Comment by timukas** [comment]
Pulled latest & greatest - IP sorting is now more logical.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/6acb9fdb-18f4-43fe-bc97-6db38ee573bd)

**Comment by its-a-feature** [comment]
awesome! I'll go ahead and close this one out then
