### ISSUE TITLE
Tasks page and task view has too little information.

### ISSUE THREAD

**Issue by timukas** [its-a-feature/Mythic#348]
Tasks page shows very useful information, however it's not that easy to understand on which callback the task was executed.

![image](https://github.com/its-a-feature/Mythic/assets/1915618/2f9021ab-6d5a-4df3-a94f-c11e9aa8af80)

Similar is on 'Task View' page. 

![image](https://github.com/its-a-feature/Mythic/assets/1915618/0be6c7f0-e641-41d5-8472-85ad7686221f)

May be adding some additional information would make those pages more readable/understandable where (on what callback/host) the command was executed?

**Comment by its-a-feature** [comment]
Just pushed an update that should help with the information you're seeing here. If you can pull that and let me know what you think?

**Comment by timukas** [comment]
Will check it later, and let you know here.

**Comment by timukas** [comment]
Just tested latest UI release.

Now definitely UI usage is more efficient. From almost any place (except split tasking/split callback)  you can quickly jump to callback session and have all information at your fingertips.

Although, during the tests i discovered one thing. If you need to have some evidences from task output for further processing (screenshots to share with team mates or adding screenshots to the reports), then in my opinion, showing IP address of callback host would be just perfect. 
There's no need to show all callback IP addresses (some machines might have several IPs and then it will look pretty ugly), would be enough to show just one IP address, same as in the main callback table view.


![image](https://github.com/its-a-feature/Mythic/assets/1915618/8c9f79bc-710e-450c-a3c2-ad12c9278ec6)

**Comment by its-a-feature** [comment]
I'm going to close this one since I think all of these pieces are now addressed in the UI. If not, feel free to re-open and comment here
