### ISSUE TITLE
starting program? Empty the docker image? ? ?

### ISSUE THREAD

**Issue by rgzn-aiyun** [its-a-feature/Mythic#35]
The previous docker image is gone, can anyone tell me what happened? ? ?

**Comment by rgzn-aiyun** [comment]
@its-a-feature

**Comment by its-a-feature** [comment]
I'm gonna need a bit more information. What do you mean?

**Comment by rgzn-aiyun** [comment]
> I'm gonna need a bit more information. What do you mean?

All other images that docker ran before were deleted!

**Comment by its-a-feature** [comment]
to help save space the helper scripts try to prune and clean up dangling containers. all of mythic/apfell's data is saved to disk/stored in the database though, so simply removing the containers doesn't remove the data. you have to specifically do the `reset_database` script to clear out the database information and `reset_operation_files` script to remove the files download/uploaded.

**Comment by rgzn-aiyun** [comment]
> to help save space the helper scripts try to prune and clean up dangling containers. all of mythic/apfell's data is saved to disk/stored in the database though, so simply removing the containers doesn't remove the data. you have to specifically do the `reset_database` script to clear out the database information and `reset_operation_files` script to remove the files download/uploaded.

There are other containers in docker, which are now deleted.

**Comment by rgzn-aiyun** [comment]
It cleaned up some very important docker images.

**Comment by its-a-feature** [comment]
oh man that sucks :/ It's on my list to programmatically determine which containers were added as part of mythic (since you can add your own) and only apply those support scripts to those. for reference, this is happening in the helper scripts `start_mythic` `stop_mythic` and the ones associated with the `start_payload_types` etc

**Comment by its-a-feature** [comment]
so you can comment out the lines that do the pruning

**Comment by rgzn-aiyun** [comment]
> so you can comment out the lines that do the pruning

You should state this in the documentation. Obviously, because don’t know in advance, all containers are cleared.

**Comment by its-a-feature** [comment]
Just pushed an update that removes extra uses of `docker prune` and the few uses that are left use a specific `--filter label=name=[name of docker container in question here]`. Sorry that ended up happening to you :/ my Mythic servers don't have any other docker containers running on them, so it didn't cross my mind.
