### ISSUE TITLE
it seems the docs might be outdated

### ISSUE THREAD

**Issue by captainkyd** [its-a-feature/Mythic#354]
Happy to help rewrite them, but I need to know the current methodoloy to get everything up and running correctly. So far following the instructions. If a dev could walk me through it some of it I can start working on that. :-D

**Comment by its-a-feature** [comment]
Hey! Always happy to have help :) What issue are you running into and where do you think the docs are outdated so I can help out?

**Comment by captainkyd** [comment]
Installing doesn’t work as described in the documentation. It partially
installs, however the ui is not part of what actively installs. Also
dependency info also isn’t readily available so deff something needs to be
updated so all of that is prominent in the documentation

**Comment by captainkyd** [comment]
Also the command build_ui fails to actually build the ui which is why I
assume there’s a dependency issue and since they aren’t included in the
documentation that I can see it means an insurmountable brick wall gets hit

**Comment by its-a-feature** [comment]
Can you describe what you mean when you say the `ui is not part of what actively installs`? When you run a `sudo ./mythic-cli status` do you not see a `mythic_react` container? 
So maybe a few clarification things are useful here:

- When starting / installing Mythic, the UI is already pre-compiled and served from an nginx server in the `mythic_react` container
- If you set `MYTHIC_REACT_DEBUG="true"`, then run `sudo ./mythic-cli build mythic_react`, you'll actually switch from serving a static website to building a react hot-reload development server within your `mythic_react` container. With that, you should still be able to view and use Mythic as normal, but if you make changes to the src in `MythicReactUI`, then you'll actually see those changes appear in your UI (it's a live dev server). When you're done making changes to the UI and want to kind of "save" those changes off to the static build, that's when you run `./mythic-cli build_ui`. It's a shortcut to build the React UI and move the final static files into that nginx static server.

So, you, as a normal user, shouldn't ever have to set that debug to true _or_ run the `build_ui` subcommand unless you're actually trying to manipulate and change the Mythic UI.

All the more reason to figure out why your normal install failed. If you give me more information about the status of your containers when you did a fresh install, I can try to help figure out what's up and then we can adjust the documentation as needed.

**Comment by captainkyd** [comment]
Shit man sorry. Your reply went to my spam so I’m just now seeing this WAY
late. I believe what you meant to say was “build_ui” at least if the ui
part was quoting me. It’s been so long though 🤷‍♀️. I believe I was
referencing the failing line of code. I have since hacked to all together
and have a working copy. Not sure what the solution was though.

**Comment by captainkyd** [comment]
Also I’m fairly certain I never used those, but what I would have done is
dive into the script in front of me that wasn’t failing. I may or may not
smoke a lotta weed so my memory can get fuzzy, but what I’d say is take
what I said and directly look at whatever script it is that is muggles
would use to install after a git clone and see if them lines are in it. If
so, there’s a good bet that’s where the error was or appeared to be. Idk.
I’ll dig into it in a bit and see if I cannot come up with something more
for ya. Pretty sure I simply attempted the build on my cloud server and
deff know that one worked. Again sorry for the delayed replies. An
overzealous spam bin won that first round, I’ll see what I can dig up n get
back to ya
