### ISSUE TITLE
Agent RSA Key Exchange Base64 Error

### ISSUE THREAD

**Issue by Ne0nd0g** [its-a-feature/Mythic#355]
When a Merlin Agent attempt to authenticate to Mythic the following error is shown in the Mythic user interface

> failed to base64 provided public key: illegal base64 data at input byte 0

I narrowed the problem down to https://github.com/its-a-feature/Mythic/pull/285 in 52ac9306f63bc38fc8685d6fad031a35eac9095a by validating that things work as expected for the commits prior to this one. I haven't yet identified exactly where the problem is in the code. I was using the Merlin Agent and HTTP C2 profile commits as shown below:
- [Merlin Agent](https://github.com/MythicAgents/merlin): `80652623d0b6e11da7ec20cb945e6a7afa3ae54b`
- [HTTP C2 Profile](https://github.com/MythicC2Profiles/http): `3006f05bea8b43c99d6978ce961d9eeb6e37c3f3`

**Comment by its-a-feature** [comment]
Fixed in v3.2.6
