### ISSUE TITLE
Unable to update operator admin status without Admin permissions

### ISSUE THREAD

**Issue by ZerkerEOD** [its-a-feature/Mythic#356]
Hello, just setup a new instance for the update and in doing so, I have tried both my account that is admin and the default mythic_admin account. I have clicked all of the additional accounts that are not admin status and every time I click the toggle I get that error message. This screenshot was taken while logged into the mythic_admin account. I also tried logging out and logging back in.

![image](https://github.com/its-a-feature/Mythic/assets/26573385/960267d3-b5b6-4daf-ac2d-550807745785)

**Comment by its-a-feature** [comment]
Good catch! Looks like the backing graphql files didn't get added to the commit. I just pushed a new version, v3.2.8, that has those files added. You should be able to do a `git pull` and then `sudo ./mythic-cli start mythic_graphql` and be good to go

**Comment by ZerkerEOD** [comment]
@its-a-feature, pulling and restarting graphql fixed it! Thanks for a quick fix!
