### ISSUE TITLE
ResilientConfig: Enhancing Stability in MythicReactUI

### ISSUE THREAD

**Issue by gak3r** [its-a-feature/Mythic#363]
Hello 🙋‍♂️,

I've come across a issue in the `MythicReactUI/src/components/MythicComponents/MythicSavedUserSetting.js` and other files that needs attention. The current codebase does not fully support upgrades from previous versions without clearing the database. This oversight is particularly evident in the way `localStorageSetting` is handled.

In the existing code, the problematic line is:
```javascript
initialStorageSetting = (localStorageSetting.toLowerCase() === "true");
```
❌

This implementation assumes `localStorageSetting` is always non-null, which isn't the case, especially when upgrading from older versions. This leads to a `TypeError` when `localStorageSetting` is null.

To ensure compatibility and robustness, I propose the following modification:
```javascript
initialStorageSetting = (localStorageSetting && localStorageSetting.toLowerCase() === "true");
```
✅

This change checks for the existence of `localStorageSetting` before calling `toLowerCase()`, thereby preventing the TypeError. It's a simple yet effective solution that will make the system more resilient and upgrade-friendly.

I strongly recommend implementing this fix in the `MythicReactUI/src/components/MythicComponents/MythicSavedUserSetting.js` and other files to enhance the system's stability and maintain compatibility with previous versions.

Thank you 🙏 for your dedication to maintaining and improving the codebase. Looking forward to seeing this issue resolved soon.

Best regards,
GaK3r 🇺🇦

**Comment by its-a-feature** [comment]
This should be fixed in the latest release, thank you for bringing it to my attention!
