### ISSUE TITLE
Latest updates do not start Mythic properly

### ISSUE THREAD

**Issue by offsecj** [its-a-feature/Mythic#365]
Hello, I've pulled and ran Mythic few times over the last days. With the latest updates (Feb 6, 2024), the rabbitmq container doesn't pull and start on a brand new ubuntu system due to which login to the web console is not possible. Followed standard installation steps as per documentation.

**Comment by offsecj** [comment]
![Screenshot 2024-02-07 102648](https://github.com/its-a-feature/Mythic/assets/121554342/19d2e9b8-9c62-4b2e-a1da-0b9812a7e1e5)

**Comment by its-a-feature** [comment]
Thank you for noticing! I added a new command to `mythic-cli` for `mythic-cli config help [env name]` that allows you to get more context around the environment variables that Mythic uses and what they mean. As part of that, it appears I accidentally copied over one of the default values for `rabbitmq_host`. A new version just finished building - `v0.0.3.10`. Can you give that one a try?

**Comment by offsecj** [comment]
Hi Cody, thanks so much for the quick response. Everything is working fine now. Felt like it was a minor adjustment needed, thanks for saving me troubleshooting time. :) Much appreciated
