### ISSUE TITLE
mythic jupyter permission denied

### ISSUE THREAD

**Issue by Ar-ALN** [its-a-feature/Mythic#369]
Hello,

Just after first installation, i'm having the issue "Permission denied: Untilted.ipynb" when trying to create a new notebook.
I tried to modify the docker compose but its not working.

Any idea about this problem ?

**Comment by its-a-feature** [comment]
I haven't seen that before, but let's see if we can track down what's going on. There should be a series of `JUPYTER_*` variables in your `Mythic/.env` file, and one of them is `JUPYTER_USE_VOLUME` - is that one set to true or false? If that one is `false`, then in the docker-compose file you'll see your local file system mounted into the container to host those ipynb files. If it's set to true, then docker uses a custom volume, `mythic_jupyter_volume` to save that data. If you're using your local file system, i'd suggest looking at the permissions on the folder to make sure nothing got changed. If you're using the volume, you can try deleting the volume and restarting jupyter (`sudo ./mythic-cli volume rm mythic_jupyter_volume` and `sudo ./mythic-cli start jupyter`)

**Comment by its-a-feature** [comment]
Were you able to test this or get more information?

**Comment by Ar-ALN** [comment]
Yes actually on vacation, don't close this ticket pls gonna get the informations you want when i return

**Comment by its-a-feature** [comment]
I'm going to close this for now, but if you're still running into the issue let me know and we can re-open it to troubleshoot some more
