### ISSUE TITLE
Token Expiration

### ISSUE THREAD

**Issue by hayicle** [its-a-feature/Mythic#37]
Hi @its-a-feature,

For generated Token  for user. When i created a new token and use it - it expired after 8 hours (already try the Re-active De-active features but didn't work for expired token) .I checked the change logs and got this in version 1.4  .
"8hr default token expiration and browser will auto-renew periodically so that  there are fewer interruptions in longer ops"

Is there anyway we can separate the token generate for browser and permanently token ?

Thanks and Regards,
<img width="1655" alt="Screen Shot 2020-09-16 at 09 58 59" src="https://user-images.githubusercontent.com/19665431/93287333-7208ef80-f803-11ea-89bb-e2df41f59029.png">

**Comment by its-a-feature** [comment]
Yup! The intent is exactly that - those tokens shouldn't expire. Which means there's a bug. Thanks for reporting and I'll try to address ASAP

**Comment by its-a-feature** [comment]
For reference, how are you using that token in your request?
Try using the header `apitoken` with the value of your token.

**Comment by hayicle** [comment]
FYi, i tested in both headers
```
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MDAxNjQyNzgsInNjb3BlIjpbImF1dGg6YXBpdG9rZW5fdXNlciIsImFkbWluIiwiT3BlcmF0aW9uIENoaW1lcmEiLCJwb2MiXX0.voYunxcMTNxwQkjum3wEgJvyp50Lsut2CrFWGuaqx8M
Cookie: access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MDAxNjQyNzgsInNjb3BlIjpbImF1dGg6YXBpdG9rZW5fdXNlciIsImFkbWluIiwiT3BlcmF0aW9uIENoaW1lcmEiLCJwb2MiXX0.voYunxcMTNxwQkjum3wEgJvyp50Lsut2CrFWGuaqx8M
```

**Comment by its-a-feature** [comment]
Try as `apitoken: eyJ0e...` for your header

**Comment by hayicle** [comment]
Thanks, i will 👍

**Comment by its-a-feature** [comment]
awesome! That's definitely my bad and a failure to document that properly :/ I'll get that updated in the documentation soon. Thanks for catching that :)
