### ISSUE TITLE
ailed to connect to RabbitMQ, retrying in 10s

### ISSUE THREAD

**Issue by websecer** [its-a-feature/Mythic#372]
`2024/03/20 19:37:08 [*] Waiting for RabbitMQ to come online (Retry Count = 10)
2024/03/20 19:37:08 [*] Attempting to connect to RabbitMQ at 127.0.0.1:5672, attempt 1/10
2024/03/20 19:37:08 [-] Failed to connect to RabbitMQ, retrying in 10s
2024/03/20 19:37:18 [*] Attempting to connect to RabbitMQ at 127.0.0.1:5672, attempt 2/10
2024/03/20 19:37:18 [-] Failed to connect to RabbitMQ, retrying in 10s
2024/03/20 19:37:28 [*] Attempting to connect to RabbitMQ at 127.0.0.1:5672, attempt 3/10
2024/03/20 19:37:28 [+] Successfully connected to RabbitMQ at amqp://mythic_user:***@127.0.0.1:5672/mythic_vhost

2024/03/20 19:37:28 [*] Waiting for Mythic Server and Nginx to come online (Retry Count = 10)
2024/03/20 19:37:28 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 1/10
2024/03/20 19:37:28 [+] Successfully connected to Mythic at https://127.0.0.1:7443

MYTHIC SERVICE		WEB ADDRESS							BOUND LOCALLY
Nginx (Mythic Web UI)	https://127.0.0.1:7443						 false
Mythic Backend Server	http://127.0.0.1:17443						 true
Hasura GraphQL Console	http://127.0.0.1:8080						 true
Jupyter Console		http://127.0.0.1:8888						 true
Internal Documentation	http://127.0.0.1:8090						 true
													
ADDITIONAL SERVICES	ADDRESS								BOUND LOCALLY
Postgres Database	postgresql://mythic_user:password@127.0.0.1:5432/mythic_db	 true
React Server		http://127.0.0.1:3000/new					 true
RabbitMQ		amqp://mythic_user:password@127.0.0.1:5672			 true
													
Mythic Main Services
CONTAINER NAME		STATE		STATUS					MOUNT	PORTS
mythic_documentation	running		Up 20 seconds (health: starting)	local	8090/tcp -> 127.0.0.1:8090
mythic_graphql		running		Up 20 seconds (health: starting)	N/A	8080/tcp -> 127.0.0.1:8080
mythic_jupyter		running		Up 20 seconds (healthy)			local	8888/tcp -> 127.0.0.1:8888
mythic_nginx		running		Up 21 seconds (health: starting)	local	7443/tcp -> :::7443, 7443
mythic_postgres		running		Up 20 seconds (health: starting)	local	5432/tcp -> 127.0.0.1:5432
mythic_rabbitmq		running		Up 20 seconds (health: starting)	local	5672/tcp -> 127.0.0.1:5672
mythic_react		running		Up 20 seconds (health: starting)	local	3000/tcp -> 127.0.0.1:3000
mythic_server		running		Up 20 seconds (health: starting)	local	7000/tcp -> :::7000, 7001/tcp -> :::7001, 7002/tcp -> :::7002, 7003/tcp -> :::7003, 7004/tcp -> :::7004, 7005/tcp -> :::7005, 7006/tcp -> :::7006, 7007/tcp -> :::7007, 7008/tcp -> :::7008, 7009/tcp -> :::7009, 7010/tcp -> :::7010, 17443/tcp -> 127.0.0.1:17443, 17444/tcp -> 127.0.0.1:17444, 7000, 7001, 7002, 7003, 7004, 7005, 7006, 7007, 7008, 7009, 7010
												
Installed Services
CONTAINER NAME	STATE	STATUS	MOUNT
					
2024/03/20 19:37:28 [*] There are no services installed
2024/03/20 19:37:28     To install one, use "sudo ./mythic-cli install github <url>"
2024/03/20 19:37:28     Agents can be found at: https://github.com/MythicAgents
2024/03/20 19:37:28     C2 Profiles can be found at: https://github.com/MythicC2Profiles
2024/03/20 19:37:28 
[*] RabbitMQ is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
2024/03/20 19:37:28 
    Use 'sudo ./mythic-cli config set rabbitmq_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
2024/03/20 19:37:28 
[*] MythicServer is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
2024/03/20 19:37:28 
    Use 'sudo ./mythic-cli config set mythic_server_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
2024/03/20 19:37:28 [*] If you are using a remote PayloadType or C2Profile, they will need certain environment variables to properly connect to Mythic.
2024/03/20 19:37:28     Use 'sudo ./mythic-cli config service' for configs for these services.
`

**Comment by its-a-feature** [comment]
What's the issue you're seeing? 
I see it successfully connected to rabbitmq:
```
2024/03/20 19:37:28 [] Attempting to connect to RabbitMQ at 127.0.0.1:5672, attempt 3/10
2024/03/20 19:37:28 [+] Successfully connected to RabbitMQ at amqp://mythic_user:***@127.0.0.1:5672/mythic_vhost
```
and connected to the web ui 
```
2024/03/20 19:37:28 [] Attempting to connect to Mythic UI at https://127.0.0.1:7443/, attempt 1/10
2024/03/20 19:37:28 [+] Successfully connected to Mythic at https://127.0.0.1:7443/
```

**Comment by its-a-feature** [comment]
Are you able to provide more context? Since it appears that everything is working, I'm going to close this issue. If you're still having issues, feel free to comment and we can re-open the issue to figure out what's going on.
