### ISSUE TITLE
How to maintain persistence

### ISSUE THREAD

**Issue by Kadoronel** [its-a-feature/Mythic#376]
How to maintain persistence on machine with apollo as agent and http for profile because after a new restart of the machine Mythic is no longer able to reconnect directly

**Comment by its-a-feature** [comment]
Apollo doesn't have any built-in persistence mechanisms. I'd suggest checking out something like https://www.hexacorn.com/blog/2017/01/28/beyond-good-ol-run-key-all-parts/ for lots of options of ways you can potentially gain persistence on a Windows host. Once you get persistence, then when Apollo is executed again you should have a new callback

**Comment by Kadoronel** [comment]
which agent works persistently

**Comment by its-a-feature** [comment]
All of the agents will work if you set up persistence first. Most agents don't offer a built-in way of performing persistence because then that exact implementation is easily signatured by defensive products and it becomes an unusable technique.

**Comment by Kadoronel** [comment]
the persistence configuration is done at what stage then

**Comment by Kadoronel** [comment]
if I take Athena for example at what stage persistence should be configured

**Comment by its-a-feature** [comment]
I think that question is up to your assessment and objectives. If you need elevated access for the persistence technique you're trying to do and you don't have it, then you'd need to privilege escalate first. If you're using a persistence technique where you don't need elevated access and you don't have it, then you're good to go. 

Regardless, you will need to do persistence after you already have an established callback from the host or some other way of remotely accessing the host.

**Comment by Kadoronel** [comment]
I understand, but when you have direct administrator access, does the application allow you to set up persistence?

**Comment by its-a-feature** [comment]
Yes, you can run commands through `assembly_inject`, `execute_assembly`, `execute_coff`, `execute_pe`, `inline_assembly`, `powerpick`, `reg_write_value`, `run`, `sc`, `shell`, `shinject` to set up and kick off whichever persistence technique you'd like to leverage. None are built-in though, so you'll need to manually set it up by executing commands or binaries through the above commands.

**Comment by Kadoronel** [comment]
a line to this method will help me

**Comment by its-a-feature** [comment]
A line to what? There are a lot of different ways to establish persistence on a Windows host (that link above has many of them). I suggest looking through that to see what kind of persistence you want to create, then looking through the steps to create it, and finally using the above commands to get it set up via Apollo. There's no one command to create persistence automatically.

**Comment by iilegacyyii** [comment]
![image](https://github.com/its-a-feature/Mythic/assets/68760809/aaa938e2-1cad-4a6d-9070-027270fbfdd5)

**Comment by its-a-feature** [comment]
I'm gonna close this issue before it gets even more off-topic.
