### ISSUE TITLE
Bug: The `download` command from Atlas Payload seems not working.

### ISSUE THREAD

**Issue by hayicle** [its-a-feature/Mythic#38]
Hi @its-a-feature,

As i tested the download feature from Atlas Payload.

<img width="1659" alt="Screen Shot 2020-10-05 at 17 24 27" src="https://user-images.githubusercontent.com/19665431/95068940-34c3bd80-0730-11eb-949b-4aa10e8b3739.png">

Could you please have a look ?
Thanks in advance ^^!.

**Comment by its-a-feature** [comment]
Happy to help! Could you show what the actual error is for the download command? Is it returning anything?

**Comment by hayicle** [comment]
No, It's not. But the status is changed from "submitted" to "error" "immediately" (drop the state "processing")
<img width="982" alt="Screen Shot 2020-10-06 at 08 34 04" src="https://user-images.githubusercontent.com/19665431/95148906-b8bc8a80-07ae-11eb-8db5-86d4b1c6d748.png">

**Comment by its-a-feature** [comment]
Gotcha, I know what the issue is, but it looks like there might be more than one. Currently working on a fix

**Comment by its-a-feature** [comment]
Fixed this, but it was tied into a bigger update that was too annoying to try to split out. So, just updated the code to 2.1. Which means to get the update, you'll have to reset your database (i.e. lose all work, so don't do it unless you absolutely need to).

**Comment by hayicle** [comment]
Thank you.
