### ISSUE TITLE
mythic_postgres container cannot run when POSTGRES_USE_VOLUME=true

### ISSUE THREAD

**Issue by kernel-sanders** [its-a-feature/Mythic#393]
The issue is the postgres config file copied into the container is called `postgres.conf` but the command line expects `postgresql.conf`.

The copy line is `COPY ["postgres.conf", "/etc/postgres.conf"]` from [here](https://github.com/its-a-feature/Mythic/blob/2079bd7ff096a2c10b57c1070b6df6c37745e382/postgres-docker/Dockerfile#L4).

The command line for the docker compose file is: `pStruct["command"] = "postgres -c \"max_connections=100\" -p ${POSTGRES_PORT} -c config_file=/etc/postgresql.conf"` from [here](https://github.com/its-a-feature/Mythic/blob/2079bd7ff096a2c10b57c1070b6df6c37745e382/Mythic_CLI/src/cmd/internal/serviceMetadata.go#L62).

This is not an issue if `POSTGRES_USE_VOLUME` is set to false because of the [mapping is set correctly](https://github.com/its-a-feature/Mythic/blob/2079bd7ff096a2c10b57c1070b6df6c37745e382/Mythic_CLI/src/cmd/internal/serviceMetadata.go#L77) to postgresql.conf

When a user tries to run Mythic with `POSTGRES_USE_VOLUME=true` the `mythic_postgres` container just restarts with the logs showing:

```
mythic_postgres  | postgres: could not access the server configuration file "/etc/postgresql.conf": No such file or directory
```

I think the simplest fix would be to update the docker container to copy in the config to `/etc/postgresql.conf` and push a new container to the registry.

**Comment by its-a-feature** [comment]
Good catch! That should be fixed when this ( https://github.com/its-a-feature/Mythic/actions/runs/10148225060 ) finishes building
