### ISSUE TITLE
My Mythic C2 not connecting after installation

### ISSUE THREAD

**Issue by maxwellgolden** [its-a-feature/Mythic#394]
HELLO,

I've been having constant issues connecting with Mythic c2.

please how can i fix it

![Screenshot from 2024-07-30 23-11-34](https://github.com/user-attachments/assets/90a11b35-2bbb-4531-8875-3f65a7e3df49)

**Comment by its-a-feature** [comment]
can you share a bit more of what's happening at the top of that output? It looks as though there's an issue with docker on your Kali instance.

**Comment by maxwellgolden** [comment]
here it is
![Uploading Screenshot from 2024-07-31 06-10-55.png…]()

**Comment by maxwellgolden** [comment]
here it is.
![Uploading Screenshot from 2024-07-31 06-10-55.png…]()

**Comment by maxwellgolden** [comment]
![Uploading Screenshot from 2024-07-31 06-10-55.png…]()

**Comment by maxwellgolden** [comment]
here it is.
![Screenshot from 2024-07-31 06-24-01](https://github.com/user-attachments/assets/333b108f-a81e-4f0c-afa7-caf171b94eae)

**Comment by maxwellgolden** [comment]
tried fixing it for the past two days but to no avail.
![Screenshot from 2024-07-31 06-25-32](https://github.com/user-attachments/assets/7b1d144c-d6fd-4fb0-afbd-7543b28cb38e)

**Comment by its-a-feature** [comment]
so right at the top it says `compose is not a docker command`, which means you don't have docker compose installed on the system. It seems like Kali did something recently that broke their installation of Docker and Docker compose (I've seen a bunch of errors with `docker-compose` and a bunch of people unable to to install the compose plugin on Kali. Somebody from the bloodhound slack suggested this worked for them:

```
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod a+x /usr/local/bin/docker-compose
apt-get install docker.io
```

So you can give that a try?

**Comment by maxwellgolden** [comment]
Alright thanks.

**Comment by maxwellgolden** [comment]
Hello, the issue still persist
![Screenshot from 2024-08-01 23-36-00](https://github.com/user-attachments/assets/ace9200a-f7bc-4b04-bb33-736e26a3917b)

**Comment by adityabaronia** [comment]
Give more than 1 core to your VM. This will remove the error for Creating mythic_graphql mythic_postgres, mythic_server and mythiv_rabbitmq.

**Comment by maxwellgolden** [comment]
Ok

**Comment by its-a-feature** [comment]
in your `Mythic/.env` file you'll see a lot of options to configure how Mythic runs. By default, Mythic (using docker compose) allocates 1VCPU to installed services (agents, c2 profiles, etc) and 2VCPU to Mythic's core functionality. This is configurable in the .env file though if you look for the settings with _cpus. You can set all the 2s to 1s and then run `sudo ./mythic-cli start` again. The performance might just be a bit worse as you only have one cpu to share for everything.

**Comment by maxwellgolden** [comment]
rabbitmq isnt connecting. 

![Screenshot from 2024-08-02 19-51-26](https://github.com/user-attachments/assets/1661e16f-31bd-44fb-b4d5-020ab5ebbd4f)

**Comment by its-a-feature** [comment]
can you share the output of `sudo ./mythic-cli logs mythic_server` and `sudo ./mythic-cli status`?

**Comment by its-a-feature** [comment]
If you're still having this issue, we can reopen and see what's going on, but since I haven't heard from you in a while I'm going to close this one
