### ISSUE TITLE
I can't log into mythic

### ISSUE THREAD

**Issue by whoami-www** [its-a-feature/Mythic#398]
![image](https://github.com/user-attachments/assets/91766c0e-8699-401f-9b15-8eff17116875)
tarting mythic_react                   ... done
ERROR: for 027ce3f4ac37_mythic_postgres  Cannot create container for service mythic_postgres: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs a
Starting mythic_nginx                   ... done
Recreating b1c4a17a5009_mythic_jupyter  ... error
ERROR: for mythic_server  Cannot create container for service mythic_server: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available
Starting mythic_documentation           ... done
ERROR: for b1c4a17a5009_mythic_jupyter  Cannot create container for service mythic_jupyter: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available

ERROR: for mythic_graphql  Cannot create container for service mythic_graphql: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available

ERROR: for mythic_rabbitmq  Cannot create container for service mythic_rabbitmq: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available

ERROR: for mythic_postgres  Cannot create container for service mythic_postgres: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available

ERROR: for mythic_server  Cannot create container for service mythic_server: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available

ERROR: for mythic_jupyter  Cannot create container for service mythic_jupyter: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available
ERROR: Encountered errors while bringing up the project.
[*] Failed to find SSL certs for Nginx container, generating now...
[+] Successfully generated new SSL certs
2024/08/16 15:22:14 [-] Service mythic_rabbitmq should be running on the host, but isn't. Containers will be unable to connect.
Start it by starting Mythic ('sudo ./mythic-cli mythic start') or manually with 'sudo ./mythic-cli mythic start mythic_rabbitmq'
2024/08/16 15:22:14 [*] Waiting for Mythic Server and Nginx to come online (Retry Count = 10)
2024/08/16 15:22:14 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 1/10
2024/08/16 15:22:14 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:22:14 Get "https://127.0.0.1:7443": read tcp 127.0.0.1:55528->127.0.0.1:7443: read: connection reset by peer
2024/08/16 15:22:24 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 2/10
2024/08/16 15:22:24 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:22:24 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:22:34 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 3/10
2024/08/16 15:22:34 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:22:34 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused

2024/08/16 15:22:44 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 4/10
2024/08/16 15:22:44 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:22:44 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:22:54 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 5/10
2024/08/16 15:22:54 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:22:54 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:23:04 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 6/10
2024/08/16 15:23:04 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:23:04 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:23:14 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 7/10
2024/08/16 15:23:14 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:23:14 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:23:24 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 8/10
2024/08/16 15:23:24 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:23:24 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:23:34 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 9/10
2024/08/16 15:23:34 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:23:34 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:23:44 [*] Attempting to connect to Mythic UI at https://127.0.0.1:7443, attempt 10/10
2024/08/16 15:23:44 [-] Failed to make connection to host, retrying in 10s
2024/08/16 15:23:44 Get "https://127.0.0.1:7443": dial tcp 127.0.0.1:7443: connect: connection refused
2024/08/16 15:23:54 [-] Failed to make connection to Mythic Server
2024/08/16 15:23:54     This could be due to limited resources on the host (recommended at least 2CPU and 4GB RAM)
2024/08/16 15:23:54     If there is an issue with Mythic server, use 'mythic-cli logs mythic_server' to view potential errors
MYTHIC SERVICE          WEB ADDRESS                                                     BOUND LOCALLY
Nginx (Mythic Web UI)   https://127.0.0.1:7443                                           false
Mythic Backend Server   http://127.0.0.1:17443                                           true
Hasura GraphQL Console  http://127.0.0.1:8080                                            true
Jupyter Console         http://127.0.0.1:8888                                            true
Internal Documentation  http://127.0.0.1:8090                                            true

ADDITIONAL SERVICES     ADDRESS                                                         BOUND LOCALLY
Postgres Database       postgresql://mythic_user:password@127.0.0.1:5432/mythic_db       true
React Server            http://127.0.0.1:3000/new                                        true
RabbitMQ                amqp://mythic_user:password@127.0.0.1:5672                       true

Mythic Main Services
CONTAINER NAME          STATE           STATUS                          MOUNT   PORTS
mythic_documentation    running         Up About a minute (healthy)     local   8090/tcp -> 127.0.0.1:8090
mythic_graphql          exited          Exited (137) 7 hours ago        N/A
mythic_jupyter          exited          Exited (0) 7 hours ago          local
mythic_nginx            restarting      Restarting (1) 44 seconds ago   local
mythic_postgres         exited          Exited (127) 7 hours ago        local
mythic_react            running         Up About a minute (healthy)     local   3000/tcp -> 127.0.0.1:3000
mythic_server           exited          Exited (2) 6 hours ago          local

Installed Services
CONTAINER NAME  STATE   STATUS  MOUNT

2024/08/16 15:23:54 [*] There are no services installed
2024/08/16 15:23:54     To install one, use "sudo ./mythic-cli install github <url>"
2024/08/16 15:23:54     Agents can be found at: https://github.com/MythicAgents
2024/08/16 15:23:54     C2 Profiles can be found at: https://github.com/MythicC2Profiles
2024/08/16 15:23:54 
[*] RabbitMQ is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
2024/08/16 15:23:54 
    Use 'sudo ./mythic-cli config set rabbitmq_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
2024/08/16 15:23:54 
[*] MythicServer is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
2024/08/16 15:23:54 
    Use 'sudo ./mythic-cli config set mythic_server_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
2024/08/16 15:23:54 [*] If you are using a remote PayloadType or C2Profile, they will need certain environment variables to properly connect to Mythic.
2024/08/16 15:23:54     Use 'sudo ./mythic-cli config service' for configs for these services.
2024/08/16 15:23:54 [*] Fetching logs from mythic_server now:
2024/08/16 15:23:54 [-] Failed to find that container

**Comment by whoami-www** [comment]
> > 错误：对于 b1c4a17a5009_mythic_jupyter，无法为服务 mythic_jupyter 创建容器：CPU 范围从 0.01 到 1.00，因为只有 1 个可用 CPU
> 
> 我经常看到这个错误。这意味着默认情况下，一些 Mythic 容器预计使用 2CPU 来工作，但您使用的 VM 只有 1 个。打开您的`Mythic/.env`文件，您会看到一堆条目，如`HASURA_CPUS="2"`和`MYTHIC_SERVER_CPUS="2"`。将所有这些`2`值更改为`1`然后`sudo ./mythic-cli start`再次运行。

ok But this error occurred again
![image](https://github.com/user-attachments/assets/181e1834-9879-40a3-8cdc-375e0c23c1be)

**Comment by whoami-www** [comment]
I used the correct account password

**Comment by whoami-www** [comment]
hi  are u online??

**Comment by whoami-www** [comment]
![image](https://github.com/user-attachments/assets/b641dd3b-2a40-420d-9927-ddecb107544f)

**Comment by its-a-feature** [comment]
That's showing a bad gateway, can you do a `sudo ./mythic-cli status`? sounds like something isn't running or having issues connecting

**Comment by its-a-feature** [comment]
I'm going to close this for now since there hasn't been any traction on it in a while. If you're still having the issue, please comment and we can reopen it
