### ISSUE TITLE
[Bug] - the runassembly and loadassembly commands of Atlas conflicted in new version

### ISSUE THREAD

**Issue by hayicle** [its-a-feature/Mythic#40]
Hi @its-a-feature ,

Me again again ^^!.

As i tested the new version to working with download command we figure out that the commands "runassembly and loadassembly" is not working at new version (old version is still good ). May you please have a look ? 

<img width="819" alt="Screen Shot 2020-10-07 at 14 45 19" src="https://user-images.githubusercontent.com/19665431/95302161-c3a91500-08ab-11eb-965d-192c07022e23.png">

Thanks in advance.

**Comment by its-a-feature** [comment]
Good catch, the parsing for the execution of assemblies was missing a space, which broke the parsing. Just pushed the fix for it
