### ISSUE TITLE
When restarting mythic all callbacks last checkin value resets to the time of restarting.

### ISSUE THREAD

**Issue by XCVYN6UGT85JywuH** [its-a-feature/Mythic#401]
![Screenshot_20240830_125829](https://github.com/user-attachments/assets/ae2f573e-12ff-4eba-bf1c-15454b652d0b)

**Comment by its-a-feature** [comment]
Ah, good catch! https://github.com/its-a-feature/Mythic/actions/runs/10633920585 <-- when that is done building, you should be able to pull the latest and have that bug fixed
