### ISSUE TITLE
Writing own agents

### ISSUE THREAD

**Issue by qwykx** [its-a-feature/Mythic#41]
Hello

A friend and me are currently working with Mythic in our Bachelor Thesis. We are writing our own agent and there might be some code we can publish afterwards. We saw you plan to write down documentation on how a GitHub repo should look like, is there already some sort of draft for that?

We are actually writing our custom Chrome Extension agent and would love some support with some further questions, unfortunately, the slack channel isn't accessible somehow.

Cheers

**Comment by its-a-feature** [comment]
Hey! That sounds awesome, happy to help. The repo I think you're referring to is this: https://github.com/its-a-feature/Mythic_External_Agent.

If you set up your GitHub repo like that, then you can use Mythic's `install_agent_from_github` script to pull it into Mythic overall. I have a blog coming out soon about this, but there's also now a MythicAgent organization (https://github.com/MythicAgents) that I can invite you to where I'm trying to get all the agents to live. It'd still be your repo under your full control, but having all of the agents live in that organization makes it easier for people to find them. 

To join the slack, you should just need to go here: https://bloodhoundgang.herokuapp.com/.
