### ISSUE TITLE
 Failed to connect to rabbitmq

### ISSUE THREAD

**Issue by pakahonta** [its-a-feature/Mythic#417]
Hello.
Once, after creating mythic agent I couldn't connect to the UI with the error 502.
**mythic-cli logs mythic_server:**
2024-10-15T18:31:36Z INF Attempting to connect to rabbitmq func=github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).GetConnection line=157
2024-10-15T18:31:36Z ERR Failed to connect to rabbitmq error="dial tcp 127.0.0.1:5672: connect: connection refused" func=github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).GetConnection line=171
2024-10-15T18:31:41Z INF Attempting to connect to rabbitmq func=github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).GetConnection line=157
2024-10-15T18:31:41Z ERR Failed to connect to rabbitmq error="dial tcp 127.0.0.1:5672: connect: connection refused" func=github.com/its-a-feature/Mythic/rabbitmq.(*rabbitMQConnection).GetConnection line=171

I reinstalled mythic, removed docker containers, reset database and I got errors above. Everytime. 

**./mythic-cli status:**
MYTHIC SERVICE          WEB ADDRESS                                                     BOUND LOCALLY
Nginx (Mythic Web UI)   https://127.0.0.1:7443                                           false
Mythic Backend Server   http://127.0.0.1:17443                                           true
Hasura GraphQL Console  http://127.0.0.1:8080                                            true
Jupyter Console         http://127.0.0.1:8888                                            true
Internal Documentation  http://127.0.0.1:8090                                            true

ADDITIONAL SERVICES     ADDRESS                                                         BOUND LOCALLY
Postgres Database       postgresql://mythic_user:password@127.0.0.1:5432/mythic_db       true
React Server            http://127.0.0.1:3000/new                                        true
RabbitMQ                amqp://mythic_user:password@127.0.0.1:5672                       true

Mythic Main Services
CONTAINER NAME          STATE           STATUS                          MOUNT   PORTS
mythic_documentation    running         Up 9 minutes (healthy)          local   8090/tcp -> 127.0.0.1:8090
mythic_graphql          running         Up 8 minutes (healthy)          N/A     8080/tcp -> 127.0.0.1:8080
mythic_jupyter          running         Up 9 minutes (healthy)          local   8888/tcp -> 127.0.0.1:8888
mythic_nginx            running         Up 9 minutes (healthy)          local   7443/tcp -> :::7443, 7443
mythic_postgres         running         Up 9 minutes (healthy)          local   5432/tcp -> 127.0.0.1:5432
mythic_rabbitmq         running         Up 9 minutes (healthy)          local   5672/tcp -> 127.0.0.1:5672
mythic_react            running         Up 9 minutes (healthy)          local   3000/tcp -> 127.0.0.1:3000
mythic_server           running         Up 9 minutes (unhealthy)        local   7000/tcp -> 127.0.0.1:7000, 7001/tcp -> 127.0.0.1:7001, 7002/tcp -> 127.0.0.1:7002, 7003/tcp -> 127.0.0.1:7003, 7004/tcp -> 127.0.0.1:7004, 7005/tcp -> 127.0.0.1:7005, 7006/tcp -> 127.0.0.1:7006, 7007/tcp -> 127.0.0.1:7007, 7008/tcp -> 127.0.0.1:7008, 7009/tcp -> 127.0.0.1:7009, 7010/tcp -> 127.0.0.1:7010, 17443/tcp -> 127.0.0.1:17443, 17444/tcp -> 127.0.0.1:17444

Installed Services
CONTAINER NAME  STATE           STATUS                          MOUNT
apollo          restarting      Restarting (1) 15 seconds ago   apollo_volume
http            running         Up 9 minutes                    http_volume

2024/10/15 18:30:37
[*] RabbitMQ is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
2024/10/15 18:30:37
    Use 'sudo ./mythic-cli config set rabbitmq_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
2024/10/15 18:30:37
[*] MythicServer is currently listening on localhost. If you have a remote Service, they will be unable to connect (i.e. one running on another server)
2024/10/15 18:30:37
    Use 'sudo ./mythic-cli config set mythic_server_bind_localhost_only false' and restart mythic ('sudo ./mythic-cli restart') to change this
2024/10/15 18:30:37 [*] If you are using a remote PayloadType or C2Profile, they will need certain environment variables to properly connect to Mythic.
2024/10/15 18:30:37     Use 'sudo ./mythic-cli config service' for configs for these services.

Can u help me? Thanks

**Comment by its-a-feature** [comment]
you got this after just generating an Apollo payload?
can you do `sudo ./mythic-cli logs apollo` as it seems that container is restarting. I'd also like to see `sudo ./mythic-cli logs mythic_rabbitmq` and `docker stats`

**Comment by its-a-feature** [comment]
ah, I bet I see the issue. This system has 2GB of RAM? That's why you're seeing these issues after creating payloads. I think you should up the resources of the system to be 4-8 GB RAM. When you get that 502 error you don't need to completely stop and uninstall Mythic either, what I believe is happening:
* you task an agent to build
* the agent starts building and during the build process spikes the memory usage
* the host sees the spiked memory and starts killing things, including containers

I bet after it finishes building, things would restart and come back online, but it will keep happening. Because these agents are dynamically compiled each time, the resources needed are a bit higher than this system appears to be providing. I'd recommend 2-4 vCPU and 4-8 GB RAM.

**Comment by pakahonta** [comment]
Thanks for the replies!
Yes, 2GB of RAM. How to remove mythic completely from my system and make a clean install?

**Comment by pakahonta** [comment]
Thanks so much! I think this question has to be closed!
