### ISSUE TITLE
ApFell HTTP Payloads Does not work with anything other than Exit Command

### ISSUE THREAD

**Issue by Logi-Ca1** [its-a-feature/Mythic#44]
Hi!

I'm just starting out with this C2, and I'm running into the following issue. I'm running the C2 server v2.1.7 on a Ubuntu 20.10 VM, with the "Victim" machine being a MacVM running Catalina 10.15.6.

With the following Payload configuration:
TargetOS: MacOS
Payload Profile: HTTP - apfell, posideon (Only changes made here is the callback host, which I set to http://<myIPaddress>)
Payload type: Apfell
commands: exit

This works fine, I get a callback to my C2.

However, if I add any other additional commands on top of exit (eg load or shell), I get the following:

![image](https://user-images.githubusercontent.com/61043353/98125542-902fc980-1eef-11eb-9c1f-f43509cda4cf.png)

I also performed a wireshark capture on the C2 server, and it looks like when I attempt a callback with the "Exit + Other commands" payload, it never actually manages to successfully perform any GET or POST requests:

![image](https://user-images.githubusercontent.com/61043353/98125783-cd945700-1eef-11eb-9511-73b4d40f4a06.png)

In contrast, the following shows a capture with a working "Exit only" payload:

![image](https://user-images.githubusercontent.com/61043353/98127253-6ecfdd00-1ef1-11eb-9455-730f1603e947.png)

As part of my troubleshooting, I have attempted to connect the two machines via WiFi and Ethernet, with the same result. I have also executed the payload on the Mac VM with and without sudo, with the same result. Is there any other troubleshooting steps I can take? Thanks!

**Comment by its-a-feature** [comment]
hm... that's very odd. Can you show me the output from going to Operational Views -> Created Payloads, then click the "Payload Actions" next to the payload with more than just the Exit command and click "View Config"? Simply adding new commands should have nothing to do with the communications. There was a similar issue before that looked kind of like this (that error anyway) and it was because they accidentally were trying to do https comms to an http server

**Comment by its-a-feature** [comment]
Also, make sure you update (we're at 2.1.8 currently)

**Comment by Logi-Ca1** [comment]
Hey, thanks for your reply!

It turns out that it was the HTTPS issue you mentioned! I saw the payload config and the callback host indeed had HTTPS! Unfortunately, I deleted the working "exit only" payload but I could have sworn it had https as the callback host as well. Weird stuff.

I guess this issue is resolved and you can put it down to me being somewhat careless. Thanks for your help in pointing out my mistake, I could have spent the whole year troubleshooting and not solve it. Cheers and thanks for your hard work in developing this fantastic C2 framework :)

**Comment by its-a-feature** [comment]
oh awesome! I'm glad it was an easy fix :) I'll make a note to try to track down that specific error to see if I can manually catch it and give a more descriptive message about what's happening
