### ISSUE TITLE
Poseidon: 'CommandParameter' object has no attribute 'default_value'

### ISSUE THREAD

**Issue by reznok** [its-a-feature/Mythic#46]
If a non-required parameter is not supplied as part of a command, it will fail to process correctly when the command is entered. I haven't fully debugged, but it appears to be due to the following lines of code:

https://github.com/its-a-feature/Mythic/blob/master/Payload_Types/poseidon/mythic/CommandBase.py#L289-L295

Where a `default_value` attribute is looked for, but does not exist in the object (`default_value` is only used to set a `value` attribute in the init).

This can be easily reproduced with the `sshauth` command:

`sshauth {"username": "root", "password": "root", "hosts": ["127.0.0.1"]}`

**Comment by reznok** [comment]
This may be `sshauth` specific, as providing `"private_key": ""` appears to bypass the error.

**Comment by its-a-feature** [comment]
Thanks for bringing that up! Turns out there were two bugs related to it! Just pushed with both updates

**Comment by its-a-feature** [comment]
git pull, start mythic again and everything should be good to go 👍
