### ISSUE TITLE
SSLv3 Ilegal Parameter Error

### ISSUE THREAD

**Issue by Iorpim** [its-a-feature/Mythic#55]
The current self signed certificate generated results in an "ERR_SSL_KEY_USAGE_INCOMPATIBLE" error when using Chrome 87, or an "sslv3 alert illegal parameter" if the certificate is imported into _ncat_.

This can be quickly fixed by adding the "-extensions v3_req" parameter to the _openssl_ command in the _start_mythic.sh_ script.

**Comment by Iorpim** [comment]
Created pull request #56 fixing the issue.

**Comment by its-a-feature** [comment]
Do you have a screenshot or more information about this error? I just tried the ssl cert generation with and without the change in your pull request but the chrome message about the cert seems the same (chrome 88).

**Comment by Iorpim** [comment]
Yes, of course.
It is possible it's a Windows only problem, although this should be the default behavior for Chrome 75+ with TLS 1.3

Chrome error:
![image](https://user-images.githubusercontent.com/22481687/105450930-50f55700-5c5a-11eb-9a16-be4e62863c0c.png)

_ncat_ error:
![image](https://user-images.githubusercontent.com/22481687/105451055-9a45a680-5c5a-11eb-9bc2-fadff6259118.png)

Chrome error when using Burp as proxy:
![image](https://user-images.githubusercontent.com/22481687/105451185-d7aa3400-5c5a-11eb-8c02-ed40e87c340e.png)

A few references to the same problem, and solution:
https://github.com/traefik/traefik/issues/5006
https://superuser.com/questions/1451895/err-ssl-key-usage-incompatible-solution
https://hexeract.wordpress.com/2019/06/13/google-chrome-75-x-a-self-signed-certificate-and-err_ssl_key_usage_incompatible/

**Comment by its-a-feature** [comment]
Thanks for the info! Merged in the associated pull request

**Comment by Iorpim** [comment]
Thanks for this great project!
