### ISSUE TITLE
Poseidon ps command issues - fix included here

### ISSUE THREAD

**Issue by asaurusrex** [its-a-feature/Mythic#63]
During some of my testing of the poseidon ps command I noticed a strange issue related to nil values appearing where they should not be.  From stack trace I and (mostly) lesnuages found that the error was related to the function _requestProcessArgumentsAndEnvironment inside of https://github.com/its-a-feature/Mythic/blob/master/Payload_Types/poseidon/agent_code/ps/rdprocess_darwin.m.  We guessed that the issue was on line 520, aka the code 
```
[tmp_env setObject: [value stringByAddingPercentEscapesUsingEncoding: NSUTF8StringEncoding]
			            forKey: parts[0]];
```

Changing this code to 
```
if (parts[0] != nil){
			[tmp_env setObject: [value stringByAddingPercentEscapesUsingEncoding: NSUTF8StringEncoding]
			            forKey: parts[0]];
			}
```
seems to resolve the issue, by making sure parts[0] is never equal to a nil value.  This is a problem because if parts[0] does equal nil it can cause a crash to a poseidon agent and kill access.

**Comment by its-a-feature** [comment]
Adding it into the new repo for poseidon on the MythicAgents organization
