### ISSUE TITLE
Feature Suggestion for Poseidon Dylibs

### ISSUE THREAD

**Issue by asaurusrex** [its-a-feature/Mythic#64]
I noticed that the current Mythic way to produce a poseidon dylib requires 4-5 steps and the user to recompile files after editing them, etc.  A much easier way to produce a dylib is to change go compilation inside https://github.com/its-a-feature/Mythic/blob/master/Payload_Types/poseidon/mythic/agent_functions/builder.py, i.e. to 
```
command += (
                "xgo -tags={} --targets={}/{} -buildmode=c-shared -out poseidon .".format(
                    profile,
                    "darwin" if self.get_parameter("os") == "darwin" else "linux",
                    "amd64",
                    "default" if self.get_parameter("mode") == "default" else "c-archive",
                )
```
In this case we use c-shared rather than the defaults for -buildmode.  Mythic will still produce a .zip file in this case, but in that zip file will be a working .dylib file which can be used with no further compilation/changes.  I figure it would be easy to offer the user this option if they would like to compile a dylib, vs going the c-archive route which requires extra steps and more work on the user's part.

**Comment by Ne0nd0g** [comment]
Feature added in https://github.com/MythicAgents/poseidon/pull/1
The Poseidon code base has moved to https://github.com/MythicAgents/poseidon/

**Comment by its-a-feature** [comment]
Since @Ne0nd0g has already incorporated this into the Mythic 2.2.2 updates in that new poseidon repository, I'll close this here.
