### ISSUE TITLE
Feature Request: Default webhook for all operations and potentially eliminate requirement for debian/ubuntu.

### ISSUE THREAD

**Issue by SurfinSafari** [its-a-feature/Mythic#65]
Would it be possible to implement an option for a default webhook  for all operations in the mythic-docker/config.json file?
I've found a solution leveraging psql to update the database and change the webhook across all ops, but a default would be really nice.

Also, it would appear the installation and startup scripts were created specifically to support debian/ubuntu. I had interest in getting this working in google container optimized OS on GCP and found some minor tweaks to the startup and shutdown scripts were necessary but definitely possible to get it working. Since Mythic is entirely container based it's relatively simple to use other containers for some of these missing dependencies.

For example, to get around the docker-compose and jq dependencies we implemented an alias into the various startup and shutdown scripts for mythic.
Below we're leveraging the docker-compose container and the toolbox container built into container optimized os.
There is a jq container but the toolbox container was easier to use on google container optimized os.
Something like the below:
```
          alias docker-compose='docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v "$PWD:$PWD" -w="$PWD" docker/compose:latest'
          function jq() {
              if [ $# -eq 3 ]; then
                  toolbox jq $1 $2 /media/root/$(pwd)/$3 2>/dev/null
              elif [ $# -eq 2 ] && [ -f "$2" ]; then
                  toolbox jq $1 /media/root/$(pwd)/$2 2>/dev/null
              elif [ $# -eq 2 ]; then
                  read -r in
                  toolbox jq $1 $2 2>/dev/null <<<$in
              elif [ $# -eq 1 ]; then
                  read -r in
                  toolbox jq $1 2>/dev/null <<<$in
              fi
          }
          alias which='command -v'
```
Thanks for your consideration.

**Comment by its-a-feature** [comment]
Hey! Good question! How are you currently creating new operations? With the 2.2 update that's coming, you can programmatically create your operations and provide initial values like:

```
MyOperation = mythic_rest.Operation(name="MyNewOperation", webhook="http://blah", channel="#mychannel", admin=mythic_rest.Operator(username="admin_username_here"))
await mythic.create_operation(MyOperation)
```

That way you can get all sorts of things auto-set for you. 

The current mythic scripts are definitely made for ubuntu/debian. Going forward I think we'll be replacing the scripts with a static golang binary or something that doesn't introduce these other dependencies. That's an interesting trick with the docker-compose alias though. So, you're passing in the docker socket into the container so that the container has the ability to control docker?

**Comment by ineffectivecoder** [comment]
We are currently just leveraging the default operation. We havent had a need to run more than 1 at a time yet.

Awesome to see the changes in the 2.2 update!

As far as some of the security implications of running docker-compose that way:
The docker-compose container we leverage is officially made by the docker team and the container is only up long enough to startup the other containers. The security risk ought to be minimal.

Thanks again.

**Comment by its-a-feature** [comment]
The latest Mythic should work for a wider variety of *nix flavors now. The `mythic-cli` is generated dynamically, and everything else runs in their own containers. There's also a default webhook/channel you can set, or you can even set a specific channel _per_ type of event. This is all set up for you in the `basic_webhook` container for you to check out too.
