### ISSUE TITLE
Missing Att&ck Techniques

### ISSUE THREAD

**Issue by Iorpim** [its-a-feature/Mythic#69]
When developing/incrementing a Payload Type certain command "attackmappings" causes it the payload break due to the fact the current _attack.json_ is missing several newly introduced techniques.

Example offending command:
```python
from CommandBase import *  # import the basics

class ExampleArguments(TaskArguments):
    def __init__(self, command_line):
        super().__init__(command_line)
        self.args = { }

    async def parse_arguments(self):
        pass

class ExampleCommand(CommandBase):
    cmd = "example"
    needs_admin = False
    help_cmd = "example"
    description = "Exemplifies issue"
    version = 1
    is_exit = False
    is_file_browse = False
    is_process_list = False
    is_download_file = False
    is_remove_file = False
    is_upload_file = False
    author = ""
    argument_class = ExampleArguments
    attackmapping = ["T1518"]  # Causes the Payload container to fail De-Sync, and stop further processing
    browser_script = None

    async def create_tasking(self, task: MythicTask) -> MythicTask:
        return task

    async def process_response(self, response: AgentResponse):
        pass
```

**Comment by Iorpim** [comment]
Pull request #70 created to fix the issue by updating the current _attack.json_ file, as well as the _attack_parse.py_ script, to Att&ck version 9.0.

**Comment by its-a-feature** [comment]
Pulled in that request (thanks!) and also updated stuff in the 2.2-updates branch so that if you put in an ATT&CK ID number that Mythic doesn't know about, it generates an alert message to the event log with the ID number, agent, and command, but continues to sync the rest of the agent information 👍
