### ISSUE TITLE
apfell  download not work

### ISSUE THREAD

**Issue by Nan3r** [its-a-feature/Mythic#72]
download {"host":"XMAC.LOCAL","path":"/tmp","file":"uuid"}
Error: untoggle for error message(s)

**Comment by its-a-feature** [comment]
I need more information to be able to help you:
* what version of Mythic are you using (you'll see it up in the top right corner)
* For that task that failed, click the red "error" status and select "Disable Browser Script" - what does the output show?

**Comment by Nan3r** [comment]
version: Mythic v2.1.18
error:
TypeError: handle.seekToFileOffset is not a function. (In 'handle.seekToFileOffset(0)', 'handle.seekToFileOffset' is undefined)

**Comment by its-a-feature** [comment]
I need to add better error handling for that, but that's due to an access denied error when trying to get a handle to the file

**Comment by Nan3r** [comment]
thanks.
