### ISSUE TITLE
PayloadType build_parameters dictionary key & BuildParameter name mismatch

### ISSUE THREAD

**Issue by Ne0nd0g** [its-a-feature/Mythic#80]
If the **PayloadType** `build_parameter` dictionary key name differs from the value's **BuildParameter** `name`, then the payload build will never return. Example broken BuildParameter:
```
        "proxy_bypass": BuildParameter(
            name="bypass proxy",
            parameter_type=BuildParameterType.ChooseOne,
            choices=["false", "true"],
            default_value="false",
            description="Ignore HTTP proxy environment settings configured on the target host?",
        ),
  ```
Limited troubleshooting showed that preventing the **BuildStatus** from being set to `Success`, or forcing it to `Error`, before return will allow the build function to complete.

Mythic will recover if the **BuildParameter** `name` is updated to match the **PayloadType** `build_parameter` key name. If the `name` is changed to not match after it was previously set to match, Mythic will continue to function as if they did match and will not re-introduce the behavior.

**Comment by its-a-feature** [comment]
This shouldn't be an issue now that the build parameters are just an array rather than the dictionary version.
