### ISSUE TITLE
Issues with the http C2 profile host header and domain fronting 

### ISSUE THREAD

**Issue by IAMPi** [its-a-feature/Mythic#92]
When configuring a C2 profile instance and you utilize the _new key type: Host_ the key name doesn't get populated correctly in Apfell.

<img width="776" alt="2021-07-08_16-56-49" src="https://user-images.githubusercontent.com/3022045/124989775-7f4ecf00-e00d-11eb-9d08-98ac89794d8b.png">

The key value ends up being empty which which is where the apfell payload pulls the header name from.

<img width="505" alt="2021-07-08_17-01-45" src="https://user-images.githubusercontent.com/3022045/124990851-e91ba880-e00e-11eb-967c-ba7aafcefe42.png">

To work around this just select a custom header and name it host

<img width="685" alt="2021-07-08_17-05-15" src="https://user-images.githubusercontent.com/3022045/124990670-ac4fb180-e00e-11eb-8679-3e6c9d946569.png">

which in turn populates the appropriate fields in the apfell payload:

<img width="272" alt="2021-07-08_17-06-14" src="https://user-images.githubusercontent.com/3022045/124990802-d608d880-e00e-11eb-807f-1b763545ea18.png">

**Comment by its-a-feature** [comment]
oh that's weird, it gets the value, but doesn't set the key, despite showing up properly in the UI and in the instance creation / view pages. good catch! I'll dive into this

**Comment by its-a-feature** [comment]
Found the bug, fixed it, merged into master: https://github.com/its-a-feature/Mythic/pull/93/commits/7e0ae8d4b0af82f345841cc421574f2e9c547992
