### ISSUE TITLE
Can't get Mythic working with Payloads

### ISSUE THREAD

**Issue by vysecurity** [its-a-feature/Mythic#94]
1. Git cloned and ./mythic-cli mythic start
2. Installed Apfell
3. Installed HTTP
4. Open web interface, go to create payloads, select MacOS.
5. Empty C2 profiles box, cannot select anything?

**Comment by its-a-feature** [comment]
Can you check some things for me?

- Are all of your payload and c2 profile containers online? `sudo ./mythic-cli status`
- Do your C2 Profile's show that they have supported payloads? It'll be in the C2 Profiles page, for the profile in question there should be a blurb that says "Supported Payload Types: ". If it doesn't list anything, restart your payload containers `sudo ./mythic-cli payload start`
