### ISSUE TITLE
Appolo agent checks in but can't be tasked..

### ISSUE THREAD

**Issue by russokiwi** [its-a-feature/Mythic#95]
Hi, I've got a call back from the agent (tried with appolo and merlin) but if I try to task it with something, there's nothing back not even a ps ? Can't see anything obvious in the logs.. Tried a clean install..Any ideas ??? Thanks!!

**Comment by its-a-feature** [comment]
Hey! so you have your callback, you issue a task, and just ... nothing happens? Nothing pops up in the UI? But you can still see the agents checking in? Which version of Mythic are you using?

**Comment by russokiwi** [comment]
2.2.9.  The UI is configured to start on 443 (I need it on 443 because of the app secuirty gateway).  The C2 profile / server are configured on 6666.  I've turned of all EDR for testing the agent, so full appolog agent is loaded fine.  Then I can see it when I go into call backs.  but whenever I try anything like get processes or file manager, the windows pop up, but have a red cross on them.  Here's some debug from the server:

 Messages will disappear when this dialog is closed.
Received Message:

Started with pid: 29...
Output: Opening config and starting instances...
Debugging statements are enabled. This gives more context, but might be a performance hit
/Mythic/c2_code/server:21: DeprecationWarning: The object should be created within an async function
  session = aiohttp.ClientSession()
++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++
Successfully using SSL for port 6666
++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++
[2021-07-10 01:13:57 +0000] [29] [INFO] Goin' Fast @ https://0.0.0.0:6666
agent_message request from: https://uri:6666/dataindex with {} and <Header('content-type': 'text/plain', 'user-agent': 'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko', 'host': 'uri:6666', 'content-length': '220', 'expect': '100-continue', 'connection': 'Close')>
 and URI: 
Forwarding along to: http://127.0.0.1:17443/api/v1.4/agent_message
agent_message request from: https://uri:6666/dataindex with {} and <Header('content-type': 'text/plain', 'user-agent': 'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko', 'host': 'uri:6666', 'content-length': '220', 'expect': '100-continue', 'connection': 'Close')>
 and URI: 
Forwarding along to: http://127.0.0.1:17443/api/v1.4/agent_message
[2021-07-10 01:13:57 +0000] - (sanic.access)[INFO][120.146.185.63:57774]: POST https://uri:6666/dataindex  200 200
[2021-07-10 01:13:57 +0000] - (sanic.access)[INFO][120.146.185.63:57779]: POST https://uri:6666/dataindex  200 200

**Comment by its-a-feature** [comment]
when you say they have a big red cross on them, can you provide a screenshot?

**Comment by russokiwi** [comment]
![Screenshot 2021-07-10 113038](https://user-images.githubusercontent.com/45227734/125147959-4d0ab200-e172-11eb-8483-bae136af45fe.png)

**Comment by its-a-feature** [comment]
ah ok yeah, that makes sense since you don't seem to be able to task anything. when you do try to task something to an agent, do you get any pop up notifications? do you see anything in the browser console?

**Comment by russokiwi** [comment]
nope, just the tabs open and that's it..

**Comment by russokiwi** [comment]
Not sure if relevant, but Getting a whole bunch of these in the error log:

[2021-07-10 01:36:30 +0000] - (sanic.access)[INFO][120.146.185.63:63434]: POST https://uri:6666/dataindex  200 200
[2021-07-10 01:36:30 +0000] - (sanic.access)[INFO][120.146.185.63:63435]: POST https://uri:6666/dataindex  200 200
agent_message request from: https://uri:6666/data with {} and <Header('content-type': 'text/plain', 'user-agent': 'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko', 'host': 'uri:6666', 'content-length': '220', 'expect': '100-continue', 'connection': 'Close')>
 and URI: 
Forwarding along to: http://127.0.0.1:17443/api/v1.4/agent_message
[2021-07-10 01:36:33 +0000] - (sanic.access)[INFO][120.146.185.63:63443]: POST https://updates.accessremote.online:6666/data  200 200

**Comment by its-a-feature** [comment]
ok that shows that you got a callback. I don't see anything that looks like an error there. it's weird that you can't task them.  when you try to issue a task to the agent, can you look in your browser console (this shows a way to do it for a few different browsers https://balsamiq.com/support/faqs/browserconsole/) and see if there are any errors listed there? Can you also look at `sudo ./mythic-cli logs mythic_server` and see if there are any errors?

**Comment by russokiwi** [comment]
Sure, 

[errorlog.txt](https://github.com/its-a-feature/Mythic/files/6794491/errorlog.txt)

From Firefox:
![Screenshot 2021-07-10 115934](https://user-images.githubusercontent.com/45227734/125148535-5564ec00-e176-11eb-99d2-ff4b8bfbb401.png)
This one's from chrome (not very helpfull)
![Screenshot 2021-07-10 115650](https://user-images.githubusercontent.com/45227734/125148508-1767c800-e176-11eb-8ac3-649837da3393.png)

**Comment by russokiwi** [comment]
Hey mate, was a user issue in the end!  Tasking is done a little differently to how i thought.  Apologies, thanks for your time!
